//MAX LEN citazione
//Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates, repellat inventore necessitatibu

module.exports = [
    {
        titolo: "The Way of the runner",
        citazione: "The purpose of training is not health or strenght, but forging the soul",
        recensione: "Il Giappone ha sempre avuto una modo di vivere totalmente estraneo a quello occidentale, nel running tuttavia queste differenze culturalisono portate all'estremo. Nella terra del sol levante infatti la corsa è uno degli sport più amati e seguiti in TV; i ragazzi frequentano team scolastici di atletica fin da giovani; le gare a staffetta sulle lunghe distanze, i cosìdetti ekiden; sono considerate gli eventi dell'anno; eppure tra tutti i campioni olimpici del fondo e del mezzofondo raramente spicca un orientale. L'autore del libro, un runner inglese che inizia ad allenarsi seguendo le metologie e i ritmi giapponesi, cerca di risolvere questo mistero; scoprendo le passioni, le motivazioni e le contraddizioni dietro al fenomeno sociale del running in Giappone. ",
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/812l4+GDnCL.jpg",
        link: "https://www.amazon.it/Way-Runner-journey-Japanese-running-ebook/dp/B00SEU8848",
    },
    {
        titolo: "The Rise of Ultrarunner",
        citazione: "'Why do you run?' 'It's the closest thing to flying'",
        recensione: "Le maratone non sono più abbastanza, la nuova frontiera del running verte sul correre per ore, se non giorni, in condizioni ambientali e climatiche avverse, 'solo' per piacere e soddisfazione personale. Che cosa spinge questi atleti a massacrare il loro corpo per raggiungere questa realizzazione personale? Che cosa spinege una persona a correre centinaia di kilometri a settimana e a fare il giro del Monte Bianco di corsa in meno di un giorno? L'autore del libro per capirlo si è messo nei panni di uno di loro, iniziando a praticare questo sport quasi da zero: oltre a intervistare gli sportivi più esperti in questo mondo, Adharanand Finn offre dei pratici consigli per chi desidera avvicinarsi a questo mondo o semplicemente vuole iniziare a correre.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/91rPEgbBOqL.jpg",
        link: "https://www.amazon.it/Rise-Ultra-Runners-Journey-Endurance/dp/1643135996",
    },
    {
        titolo: "Tu non sai cos'è la guerra",
        citazione: "Mi vergogno ad ammettere di non avere una casa... L'ho sempre trovato insopportabile, dal giorno in cui siamo fuggite.",
        recensione: "Da quando è iniziata la guerra in Ucraina siamo bombardati da tragiche notizie provenienti dall'est europa; tuttavia spesso manca il punto di vista di una gran parte della popolazione coinvolta: quella dei bambini. La giovanissima autrice di questo libro, una dodicenne ucraina costretta a scappare dalla propria città per i bombardamenti; racconta ciò che comporta la guerra nel quotidiano per la maggior parte della popolazione: mancanza di cibo, acqua e medicinali; la lontananza da casa e dai parenti ma soprattutto la semplice normalità ormai andata persa: tutto ciò che fino a poco prima dello scoppio del conflitto era dato per scontato ora appare come un sogno che non potrà mai più avverarsi.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9791221203134_0_536_0_75.jpg",
        link: "https://www.amazon.it/Tu-non-sai-cosè-guerra-ebook/dp/B0BHX12FJZ",
    },
    {
        titolo: "California",
        citazione: "Insomma, vorremmo essere un po' più come la California, che infatti da secoli è considerata la «fine del mondo»",
        recensione: "Immaginiamo tutti la California come la terra dei sogni, dove vigneti paradisiaci incontrano il surf di Malibu Beach e le celebrità di Hollywood si confondono con gli startuppari che progettano la vita di tutta la popolazione. Eppure Francesco Costa racconta come la California stia attraversando una grande crisi sociale ed economica; attribuendo la colpa di questo declino ai californiani stessi, incapaci di accettare i cambiamenti e troppo bramosi di mantenere lo status quo. Il fatto interessante è che la California non è caso isolato, l'autore avverte infatti che sono molte le realtà sociali che stanno andando in questa direzione e espone le soluzioni attuabili per non replicare gli spiacevoli fatti accaduti nello stato americano.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/71jll4IJAmL.jpg",
        link: "https://www.amazon.it/California-Francesco-Costa/dp/8804755210/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3VXSC7PW0ZB64&keywords=california+costa&qid=1666554573&qu=eyJxc2MiOiIwLjEyIiwicXNhIjoiMC4wNiIsInFzcCI6IjAuMTAifQ%3D%3D&sprefix=california+cost%2Caps%2C193&sr=8-1",
    },
    {
        titolo: "What I learned losing a million dollars",
        citazione: "You don't know why the market is going up or down, you just want to know what is doing",
        recensione : "Imparare dai propri insuccessi è la prima regola nell'imprenditoria memoria, eppure è sempre la pratica più difficile da attuare quando si tratta di affrontare un fallimento, soprattutto nel trading, dove ogni giorno milioni di persone scommettono i propri soldi senza un approcio razionale. L'autore parte proprio dalla sua esperienza di trader, inesperto ma fortunato, che attribuiva il merito dei suoi guadagni alle sue abilità e non alla fortuna, portandolo sulla strada della rovina. All'interno del libro viene quindi descritta e analizzata la tipica mentinalità americana legata al business, non mancano tuttavia aneddoti personali, storie legate alla borsa americana e concetti più teorici legati ai bias mentali che ci conducono verso certi comportamenti errati.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51fGOyjVMlL.jpg",
        link: "https://www.amazon.it/What-Learned-Losing-Million-Dollars/dp/0231164688/ref=sr_1_1?keywords=what+i+learned+losing+a+million+dollars&qid=1666554557&qu=eyJxc2MiOiIwLjQ4IiwicXNhIjoiMC4xMSIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=what+i+learn%2Caps%2C217&sr=8-1",
    },
    {
        titolo: "Antifragile",
        citazione: "E' fragile ciò che subisce perdite nell'incertezza. E' antifragile tutto il contrario.",
        recensione : "Siamo tutti convinti che il contrario di fragile sia robusto, tuttavia nessuno hai mai dato importanza al concetto di antifragililità. L'economica Taleb in questo libro approfondisce come l'abilità di rafforzarsi nelle difficoltà, nelle avversità e nella volatilità sia la qualità di ogni persona, società o comunità di successo. Dal momento che non è possibile prevedere e progettersi dai rischi e dagli imprevisti del mondo, è preferibile imparare a trarre vantaggio dal disordine e dagli errori. Facendo ciò si cambia completamente il paradigma delle proprie azioni, spesso si adotta per un approcio più pratico e spontaneo e più diffidente nei confronti dagli studi puramente teorici sulla probabilità su cui la società odierna troppo spesso si basa.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/71ly-xl-lnL.jpg",
        link: "https://www.amazon.it/Antifragile-Prosperare-disordine-Nassim-Nicholas/dp/8842819174/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1QVIMKQL0KLRP&keywords=antifragile&qid=1666554598&qu=eyJxc2MiOiIxLjA1IiwicXNhIjoiMC44MyIsInFzcCI6IjAuOTkifQ%3D%3D&sprefix=antifragile%2Caps%2C192&sr=8-1",
    },
    {
        titolo: "L'Arte dell'hacking",
        citazione: "Dal mio punto di vista, l'hacking è una pratica creativa come l'arte.",
        recensione : "Gli hacker al giorno d'oggi sono visti solo come geniali informatici che decidono di sfruttare le loro competenze per craccare software, violare la privacy e rubare soldi e dati; eppure dietro questa figura nata con l'avvento dell'informatica moderna si nasconde dietro. Un hacker non è altro una persona curiosa delle fallacie del sistema e che di conseguenza prova a trarre vantaggio da queste sue conoscenze. Quest'attitudine può avere applicazioni diverse: dall'impiego nella pubblica amministrazione, allo spionaggio militare, nelle società o le banche private o, come nella paggior parte dei casi, per puro divertimento.",
        punteggio: 4,
        src: "https://www.ibs.it/images/9788807883606_0_424_0_75.jpg",
        link: "https://www.amazon.it/Larte-dellhacking-Kevin-D-Mitnick/dp/8807883600/ref=sr_1_2?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2QEEYB59UIJYM&keywords=l%27arte+dell%27hacking&qid=1666554610&qu=eyJxc2MiOiIxLjc5IiwicXNhIjoiMS44NiIsInFzcCI6IjEuNjEifQ%3D%3D&sprefix=l+arte+dell+hacking%2Caps%2C187&sr=8-2",
    },
    {
        titolo: "Ovunque",
        citazione: "Quando viaggio da solo mi passa la voglia di cambiarmi, tanto a chi posso dar fastidio?",
        recensione : "Niccolo Balinì, meglio conosciuto sul YouTube come Human Safari, in questo libro racconta in modo molto 'leggero e chiaccherato' le sue improbabili avventure in giro per il mondo nel periodo in cui viaggiare è mancato di più: gli anni del Covid. Il mezzo di trasporto protagonista, anche viste le complicazioni legate alla pandemia; resta la sua vespa, a bordo di cui Niccolò Balini ha attraversato tutta la penisola e si è spinto oltre i confini nazionlali. Per quanto si riconosca che il libro sia scritto 'da uno youtuber', si tratta di cronache perfette per una lettura serale e disimpegnata che spinga a lasciarci alle spalle le nostre quotidianità per viaggiare senza una meta precisa, ovunque per l'appunto.",
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51xdROB0qnL.jpg",
        link: "https://www.amazon.it/Ovunque-Nicol%C3%B2-Balini/dp/8820073072/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=XQMLE4BQPBCJ&keywords=ovunque&qid=1666554620&qu=eyJxc2MiOiIxLjE1IiwicXNhIjoiMC44NyIsInFzcCI6IjEuMzIifQ%3D%3D&sprefix=ovunqu%2Caps%2C190&sr=8-1",
    },
    {
        titolo: "La Traiettoria",
        citazione: "Vengo da una famiglia dove seguire le regole è un imperativo. Per capire chi ero ho dovuto infrangerle",
        recensione : "Il cognome Benetton non ha bisogno di presentazioni, eppure Alessandro Benetton, figlio di Luciano, fondatore dello storico brand di abbigliamento omonimo e del grande gruppo industriali italiano; si cela una storia composta da imprevisti, scelte controverse in contrasto con la famiglia e una forte voglia di prendere la propria strada, indipendentemente dalle aspettative e le volontà della famiglia. La storia di Alessandro suggerisce quindi di prendersi le proprie responsabilità, intraprnedere la propria via indipendentemente dalle aspettative sociali e di rompere le regole qualora fosse necessario per raggiungere un fine ultimo personale più importante",
        punteggio: 4,
        src: "https://www.ibs.it/images/9788804749080_0_536_0_75.jpg",
        link: "https://www.amazon.it/traiettoria-Alessandro-Benetton/dp/8804749083/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=364VA79PM5XO9&keywords=la+traiettoria&qid=1666554636&qu=eyJxc2MiOiIwLjE5IiwicXNhIjoiMC4xMSIsInFzcCI6IjAuMjMifQ%3D%3D&sprefix=la+traiettori%2Caps%2C179&sr=8-1",
    },
    {
        titolo: "Giocati dal Caso",
        citazione: "Nessuno accetta il caso come causa del proprio successo, ma solo del proprio fallimento.",
        recensione : "Nella nostra vita di tutti i giorni siamo così impegnati a pianificare, prevedere e calcolare tutto che diamo poca importanza a ciò che governa le nostre vite: il caso. Un minimo cambiamento può causare conseguenze gigantesche nelle nostre vite; di conseguenza il concetto di probabilità matematica come lo conoscevamo finora diventa inutile per trarre vantaggi dalla volatilità. Taleb di conseguenza, che pur essendo un esperto matematico ed economica non apprezza inutili studi accademici e puramente teorici; invita ad assumere un approcio più empirista, a non confondere le nostre abilità con il caso e a distinguere causalità e casualità.", 
        punteggio: 4,
        src: "https://kbimages1-a.akamaihd.net/07db90c8-5875-48b7-86a0-7d73423973a5/1200/1200/False/giocati-dal-caso-1.jpg",
        link: "https://www.amazon.it/Giocati-caso-ruolo-fortuna-finanza/dp/8842820237/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2C07373FYB580&keywords=giocati+dal+caso&qid=1666554645&qu=eyJxc2MiOiIwLjcwIiwicXNhIjoiMC41MiIsInFzcCI6IjAuMzUifQ%3D%3D&sprefix=giocati+dal+cas%2Caps%2C171&sr=8-1",
    },
    {
        titolo: "CARCHITECTURE - Houses with horsepower",
        citazione: "Homes should be built in factories similar to those for automobiles",
        recensione : "Che cosa c'entra Le Corbusier con l'azienda automobilistica SAAB? CARCHITECTURE non cerca di rispondere a questa domanda in modo approfondito e tecnico, eppure riesce a mettere a confronto due mondi che spesso non sono mai accostati: l'architettura e le automobili. Non aspettatevi però un'analisi del rapporto tra queste due; prendete il libro per quello che è: una semplice ma piacevole raccolta di scatti che ritraggono architetture e macchine che, per la loro storia, per il loro stile o semplicemente per i loro proprietari; sono collegate.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/41SfoJBKnNL.jpg",
        link: "https://www.amazon.it/Carchitecture-Houses-Horsepower-Thijs-Demeulemeester/dp/9401461031",
    },
    {
        titolo: "Steve Jobs non abita qui",
        citazione: "Airbnb non è proprio come McDonald's, ma come un avocato toast sostenibile e facilmente replicabile.",
        recensione : "La Silicon Valley viene spesso descritta come il posto di lavoro da sogno, in particolare per tutti i giovani appassionati di innovazione e tecnologia; eppure non è tutto oro quel che luccica. Dietro la California da sogno si cela anche la sua controparte più faticosa, corrotta e illusa di essere sempre nel giusto. Michele Masneri compie un ritratto ironico e inusuale di questa regione che ormai detiene un vero e proprio status symbol e rappresenta un modo di divere invidiato (inspiegabilmente...?) da tutto il mondo.", 
        punteggio: 5,
        src: "https://www.adelphi.it/spool/cover__id8866_w600_t1594807353.jpg&.jpg",
        link: "https://www.amazon.it/Steve-Jobs-non-abita-pi%C3%B9/dp/8845934640/ref=sr_1_1?keywords=steve+jobs+non+abita+pi%C3%B9+qui&qid=1666554659&qu=eyJxc2MiOiIwLjM5IiwicXNhIjoiMC4yMyIsInFzcCI6IjAuMjEifQ%3D%3D&sprefix=steve+j%2Caps%2C178&sr=8-1",
    },
    {
        titolo: "La vera storia del genio che ha fondato McDonald",
        citazione: "Credo in Dio, nella famiglia e in McDonald’s - in ufficio, però, l’ordine va invertito.",
        recensione : "Se ci si vuole immergersi nella testa della mente di uno degli uomini più americani di sempre si tratta del libro giusto. Ray Kroc incarna infatti  lo stereotipo dell'uomo d'affari che, cogliendo ogni buona opportunità che gli si è presentata, è riuscito a trasformare un semplice chioschetto di 'burger and fries' nella catena di fast food più diffusa al mondo. Oltre a essere fonte di ispirazione per chi è motivato a costruire qualcosa di proprio, il libro affronta in modo pratico i problemi a cui si va in contro in termini di prodotto, gestione del personale, rapporto con il cliente e con i fornitori quando si tratta di gestire un business come McDonald's che, pur essendo diffuso globalmente; rispecchia ancora oggi l'ideale del sogno americano.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/41PADEM8WzL.jpg",
        link: "https://www.amazon.it/vera-storia-genio-fondato-McDonalds%C2%AE/dp/B07D4ZPJL9/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1UM8TB4N0M2FL&keywords=la+vera+storia+del+genio&qid=1666554671&qu=eyJxc2MiOiIwLjc4IiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=la+vera+storia+del+genio%2Caps%2C191&sr=8-1",
    },
    {
        titolo: "Helgoland",
        citazione: "La teoria dei quanti è la migliore descrizione della natura di cui disponiamo oggi.",
        recensione : "Se qualcuno dichiara di comprendere la fisica quantistica significa che chi gliel'ha spiegata non si è espresso bene. Lo stesso concetto viene più volte ribadito dall'autore durante la lettura per sottolineare quanto sia controintuiva e difficile questa branca della fisica. Carlo Rovelli tuttavia è in grado di accennarne i concetti fondamentali, a differenza de 'L'Ordine del Tempo' tuttavia, sono richieste alcune conoscenze pregresse e una mentalità abbastanza avvezza al linguaggio scientifico per comprendere i punti chiave della meccanica quantistica. Pur essendo molto complicato nei concetti; il libro utilizza un linguaggio facile e ricorre alla narrazione di divertenti aneddoti storici che ne facilitano la comprensione. ", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/617aCsvbXJL.jpg",
        link: "https://www.amazon.it/Helgoland-Carlo-Rovelli/dp/8845935051/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=BWGZ49K45D8E&keywords=helgoland&qid=1666554692&qu=eyJxc2MiOiIwLjkzIiwicXNhIjoiMC40NCIsInFzcCI6IjAuNDEifQ%3D%3D&sprefix=halgola%2Caps%2C224&sr=8-1",
    },
    {
        titolo: "Una Terra Promessa",
        citazione: "Ero diventato un politico. E nemmeno troppo bravo.",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71W0kAoWW4L.jpg",
        link: "https://www.amazon.it/Una-terra-promessa-Barack-Obama/dp/8811149878/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2VVVS5PA89EES&keywords=una+terra+promessa&qid=1666554702&qu=eyJxc2MiOiIxLjkwIiwicXNhIjoiMS42NCIsInFzcCI6IjAuNTcifQ%3D%3D&sprefix=una+terra+promess%2Caps%2C237&sr=8-1",
    },
    {
        titolo: "Corro perchè mia madre mi picchia",
        citazione: "La corsa è inutile, e proprio per questo va coltivata. Come un'arte.",
        recensione : "Essendo sia milanese che corridore come gli autori, dovevo assolutamente leggere questo libro e, proprio come mi aspettavo; la sua lettura non ha fatto altro che motivarmi e divertirmi. Così come avrebbero fatto tutti gli altri runner; mi sono completamente ritrovato e immedesimato in ogni vicenda, abitudine e pensiero narrato all'interno del libro. Se anche voi siete dei corridori questo libro potrebbe essere un titolo perfetto per una lettura disimpegnata, leggera ma molto divertente; se invece non siete molto affini all'indossare delle scarpe da running, nonostante il libro non contenga molti consigli pratici su come avvicinarsi a questo sport; potrebbe darvi la motivazione per correre i primi chilometri.", 
        punteggio: 4,
        src: "https://www.oscarmondadori.it/content/uploads/2017/08/978880464855HIG.JPG",
        link: "https://www.amazon.it/Una-terra-promessa-Barack-Obama/dp/8811149878/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2VVVS5PA89EES&keywords=una+terra+promessa&qid=1666554702&qu=eyJxc2MiOiIxLjkwIiwicXNhIjoiMS42NCIsInFzcCI6IjAuNTcifQ%3D%3D&sprefix=una+terra+promess%2Caps%2C237&sr=8-1",
    },
    {
        titolo: "Una notte ho sognato New York",
        citazione: "Bastano cinque minuti per sentirti parte di New York, ma una vita intera per capirla fino in fondo",
        recensione : "Piero Armenti, italiano trasferitosi nella Grande Mela dove ha avviato un'agenzia viaggi di successo; riesce a raccontare la storia di uno dei tanti italiani in fissa con il sogno americano. Il desiderio di vivere e lavorare negli States, che anche lui ha vissuto in età giovanile; viene quindi approfondito al meglio; includendo tutte le contraddizioni, i lati positivi e le fatiche che si celano dietro la vita sognata da tanti immigrati negli Stati Uniti d'America. ", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61vKCnaTK8L.jpg",
        link: "https://www.amazon.it/Una-notte-sognato-New-York/dp/8804724994/ref=sr_1_1?keywords=una+notte+ho+sognato+new+york&qid=1666554723&qu=eyJxc2MiOiIxLjA1IiwicXNhIjoiMC43MyIsInFzcCI6IjAuNzUifQ%3D%3D&sprefix=una+notte+h%2Caps%2C202&sr=8-1",
    },
    {
        titolo: "I Principi del Successo",
        citazione: "Confidate nella verità a tutti i costi e nella trasparenza estrema",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71LyvaUH80L.jpg",
        link: "https://www.amazon.it/principi-del-successo-Ray-Dalio/dp/8820385716/ref=sr_1_1?keywords=i+principi+del+successo+ray+dalio&qid=1666554733&qu=eyJxc2MiOiIxLjI4IiwicXNhIjoiMC44MSIsInFzcCI6IjAuOTEifQ%3D%3D&sprefix=i+principi+del+%2Caps%2C208&sr=8-1",
    },
    {
        titolo: "Il Cigno Nero",
        citazione: "Perchè ci ostiniamo a pianificare il futuro quando le nostre vite vengono modificate dall'ignoto?",
        recensione : "Un Cigno Nero non è altro che un evento unico, raro, inspiegabile a priori e che che genera un impatto enorme sulla società. Secondo Taleb sono questi fatti a governare la realtà in cui viviamo e, a causa della loro estrema indeterminatezza; tutti gli studi probabilistici e legati al rischio diventano inutili. Lo scrittore consiglia quindi di cambiare totalmente prospettiva: piuttosto che cercare di prevedere questi episodi; è meglio mettersi in una posizione in modo da poter trarre vantaggi dall'alta volalitità in cui siamo immersi. Applicare queste strategie nella vita quotidiana, eppure l'esperienza di Taleb dimostr che, soprattutto in ambito finanziario e lavorativo; la volatilità e i cambiamenti inaspettati e repentini possono portare numerosi vantaggi se affrontati correttamente.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61rsVxQlXIL.jpg",
        link: "https://www.amazon.it/cigno-nero-limprobabile-governa-nostra/dp/884282027X/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2HWYIG0PARQ2W&keywords=il+cigno+nero&qid=1666554745&qu=eyJxc2MiOiIwLjc5IiwicXNhIjoiMC40MiIsInFzcCI6IjAuNTAifQ%3D%3D&sprefix=il+cigno+ne%2Caps%2C177&sr=8-1",
    },
    {
        titolo: "La mucca viola",
        citazione: "O sei una mucca viola o non sei nessuno. O sei straordinario o non esisti.",
        recensione : "Il titolo potrebbe trarre in inganno i possibili letturi riguardo il contenuto; questo libro infatti, nonostante non sia propriamente un saggio specifico dato che utilizza un linguaggio e una narrazione accessibile a tutti, sintetizza in maniera abbastanza esaustiva e sintetica tutti i principi che dovrebbero stare alla base di un'operazione marketing di successo. Oltre che a spiegazioni più teoriche, vengono proposti numerosi case studies fallimentari e di successo che rappresentano le debolezze o i punti di forza di differenti metodi di concepire e progettare la pubblicità.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/718OGpfUOMS.jpg",
        link: "https://www.amazon.it/mucca-viola-notare-fortuna-marrone/dp/8836200559/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1QD6TIK1V14XD&keywords=la+mucca+viola&qid=1666554757&qu=eyJxc2MiOiIxLjExIiwicXNhIjoiMC40MyIsInFzcCI6IjAuMzUifQ%3D%3D&sprefix=la+mucca+viol%2Caps%2C154&sr=8-1",
    },
    {
        titolo: "La montagna dentro",
        citazione: "Appendo l'amaca. Sotto di me il vuoto, sopra di me le stelle.",
        recensione : "Nonostante pochi conoscano Herve Barmasse, l'autore di quest libro è un alplinista e scrittore molto rispettato da tutti gli amanti della montagna. Raccontando alcune sue vicende biografiche, Barmasse riesce a descrivere il suo rapporto fortissimo con la montagna e la società in cui vive, conferendo inoltre numerose lezioni sul corretto di vivere il mondo dell'alpinismo. Ovviamente all'interno del libro non sono presenti consigli tecnici su come avvicinarsi allo sci di fondo o all'arrampicata, ma sicuramente vi verrà voglia di lasciare la città e di esplorare ad alta quota a prescindere dal proprio livello di tecnica e allenamento.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788858130117_0_536_0_75.jpg",
        link: "https://www.amazon.it/montagna-dentro-Herv%C3%A9-Barmasse/dp/8858130111/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=OGPON7MJPART&keywords=la+montagna+dentro&qid=1666554768&qu=eyJxc2MiOiIxLjE4IiwicXNhIjoiMC42MiIsInFzcCI6IjAuNTYifQ%3D%3D&sprefix=la+montagna+dent%2Caps%2C160&sr=8-1",
    },
    {
        titolo: "Allegro Occidentale",
        citazione: "....E scoprì che i cinesi vedono gli occidentali tutti allo stesso modo.",
        recensione : "Il modo in cui noi occidentali viaggiamo è del tutto tragi-comico. Ce lo insegna Francesco Piccolo con questo breve, esilerante e divertente romanzo, all'interno di cui viene raccontato il viaggio di un gruppo di benestanti e 'ingenui' europei alla scoperta di un mondo che è ben diverso da come se lo immaginano. Assumendo un punto di vista differente comprendiamo infatti che la maggior parte delle volte che visitiamo un posto nuovo stiamo vedendo solamente quello che ci aspettiamo di trovare, non la verità riguardo la località; come se le nostre aspettative riguardo un contesto lontanissimo da noi dovessero necessariamente rispecchiare l'autenticità del luogo", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61H+Jg0kL+L.jpg",
        link: "https://www.amazon.it/Allegro-occidentale-Francesco-Piccolo/dp/8806227599/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2W7YH4X10OS88&keywords=allegro+occidentale&qid=1666554781&qu=eyJxc2MiOiIwLjAwIiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=allegro+occidental%2Caps%2C176&sr=8-1il ",
    },
    {
        titolo: "Il metodo Warren Buffet",
        citazione: "Ciò che mi preoccupa di più è la mcnanza di fiducia negli investimenti a lungo termine.",
        recensione : "Il libro, considerato da tutti il Sacro Graal della letteratura finanziaria, tramite il racconto della vita di Buffet; descrive la sua vincente strategia di investimento. Le metodologie presentate nel libro non sono tuttavia spendili da tutti nel breve periodo; si può però cambiare forma mentis riguardo questo settore, assumendo una mentalità molto più saggia, improntata sul lungo termine, sul valore di un'azienda e che punta a investire su ciò che realmente si conosce. Gli investimenti di Buffet prevedono infatti un orizzonte di tempo spesso superiore al decennio, si concentrato esclusivamente sulle aziende il cui business model sia facilmente comprensibile e sono sempre il risultato di un'analisi razionale e basata sul presente. ", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51q-meCl8VL.jpg",
        link: "https://www.amazon.it/metodo-Warren-Buffett-segreti-investitore/dp/8820362716/ref=sr_1_1?keywords=il+metodo+warren+buffett&qid=1666554796&qu=eyJxc2MiOiIxLjQ0IiwicXNhIjoiMC44NyIsInFzcCI6IjAuNjgifQ%3D%3D&sprefix=il+metodo+w%2Caps%2C160&sr=8-1",
    },
    {
        titolo: "Lo zen e l'arte di manutenzione della motocicletta",
        citazione: "Vivere soltanto in funzione di una meta futura è sciocco. È sui fianchi delle montagne, e non sulla cima, che si sviluppa la vita",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/41q9GMGWmeL.jpg",
        link: "https://www.amazon.it/zen-larte-della-manutenzione-motocicletta/dp/8845907341/ref=sr_1_1?keywords=lo+zen+e+l+arte+della+manutenzione+della+motocicletta&qid=1666554806&qu=eyJxc2MiOiIwLjg0IiwicXNhIjoiMC4zNyIsInFzcCI6IjAuNDQifQ%3D%3D&sprefix=lo+zen+e%2Caps%2C141&sr=8-1",
    },
    {
        titolo: "Prima persona singolare",
        citazione: "Cambiando l’esposizione dei raggi del sole, l’ombra diventa luce, la luce diventa ombra. Il positivo diventa negativo, e viceversa",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 3,
        src: "https://www.ibs.it/images/9788806248284_0_536_0_75.jpg",
        link: "https://www.amazon.it/Prima-persona-singolare-Haruki-Murakami/dp/8806248286/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=CU10USRP3RTQ&keywords=prima+persona+singolare&qid=1666554817&qu=eyJxc2MiOiIwLjQyIiwicXNhIjoiMC4xOCIsInFzcCI6IjAuMjEifQ%3D%3D&sprefix=prima+persona+singolar%2Caps%2C214&sr=8-1",
    },
    {
        titolo: "Homo Sapiens",
        citazione: "Siamo dei che si sono fatti da sè.",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 5,
        src: "https://www.ibs.it/images/9788845296499_0_536_0_75.jpg",
        link: "https://www.amazon.it/Sapiens-animali-Breve-storia-dellumanit%C3%A0/dp/8845296490/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=WEI089GNRYD0&keywords=homo+sapiens&qid=1666554827&qu=eyJxc2MiOiIyLjg1IiwicXNhIjoiMi40MCIsInFzcCI6IjIuMzYifQ%3D%3D&sprefix=homo+sapien%2Caps%2C161&sr=8-1",
    },
    {
        titolo: "Da zero a uno",
        citazione: "Il monopolio è la condizione di ogni business di successo",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71smRBsS57L.jpg",
        link: "https://www.amazon.it/segreti-startup-ovvero-costruisce-futuro/dp/8817080462/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1GMFO4F75D74D&keywords=da+zero+a+uno&qid=1666554841&qu=eyJxc2MiOiIxLjI5IiwicXNhIjoiMC44OCIsInFzcCI6IjAuNzUifQ%3D%3D&sprefix=da+zero+a+%2Caps%2C222&sr=8-1",
    },
    {
        titolo: "Tim Cook",
        citazione: "Non ho mai riconosciuta la mia sessualità pubblicamente. Quindi fatemi essere chiaro: sono fiero di esseregay",
        recensione : "Tim Cook è tutto l'opposto di Steve Jobs: un manager pubblicamente freddo; meno caricasmatico e creativo; senza una mente visionaria come il fondatore della Apple; eppure come mai è stato scelto proprio lui per succedere al geniale fondatore della Apple? Questa biografia cerca di indagarne i motivi partendo dall'infanzia di Cook, i suoi primi incarichi lavorativi e fino a mostrare le ragioni per cui è riusito a far progredire l'eredità di Jobs fino a farla diventare l'azienda  più ricca al mondo. Consiglio di leggere solo questa biografia dopo aver letto quella di Jobs, in modo da poter delinare maggiormente le differenze tra le due personalità, gli stili manageriali e i cambiamenti che vi sono stati sotto la direzione di entrambi.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/419maTdPYrL.jpg",
        link: "https://www.amazon.it/Cook-genio-cambiato-futuro-Apple/dp/8820067609/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1MZKCJRYRJQW7&keywords=tim+cook&qid=1666554850&qu=eyJxc2MiOiIxLjMxIiwicXNhIjoiMC45NyIsInFzcCI6IjAuODgifQ%3D%3D&sprefix=tim+co%2Caps%2C284&sr=8-1",
    },
    {
        titolo: "Momenti di trascurabile felicità",
        citazione: "Tutte le cose che bisogna fare, mi piace rimandarle, oppure averle già fatte.",
        recensione : "Tutti noi abbiamo i nostri intimi momenti di felicità che, in maniera inconsapevole, arricchiscono notevolmente le nostre vite ma di cui spesso ci vergognamo. Prima di leggere questo libro nemmeno ci pensavo, eppure sono queste stupide piccolezze a renderci felici nel quotidiano; non potremmo vivere altrimenti. Non vi resterà nulla di profondo da questa lettura, se non la consapevolezza che questi piccoli momenti esistono e fanno la differenza, perciò non trascurateli e non sottovalutateli. Per  questo libro non voglio far altro che incoraggiarvi a farci caso, tenere traccia di questi momenti, rileggerli quando siete annoiaiti e, quanto ne avete la possibilità, di condividerli con le persone che preferite.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61u6kJLydPL.jpg",
        link: "https://www.amazon.it/Momenti-trascurabile-felicit%C3%A0-Francesco-Piccolo/dp/8806219650/ref=sr_1_1?keywords=momenti+di+trascurabile+felicit%C3%A0&qid=1666554860&qu=eyJxc2MiOiIwLjgwIiwicXNhIjoiMC40MiIsInFzcCI6IjAuNDkifQ%3D%3D&sprefix=momenti+di+tr%2Caps%2C256&sr=8-1",
    },
    {
        titolo: "Let my people go surfing",
        citazione: "Non superare mai i tuoi limiti. Spingili al massimo e vivi per quei momenti, ma non andare oltre.",
        recensione : "Patagonia, Nike, The North Face, Carhart, Adidas...    Potrebbero sembrarci tutti brand molto simili come prodotti, marketing e origine: eppure dietro la storia e i valori di Patagonia si cela una persona carismatica quanto riservata: il suo fondatore Yvon Chouinard:  un uomo estremamente attento all'ambiente, alle sue responsabilità da imprenditore e all'impatto sociale della sua azienda. Patagonia infatti ribalta completamente tutte le lezioni sull'imprenditoria americana: non offre saldi di ogni tipo, aumenta i prezzi qualora necessario per garantire una maggiore ecosostenibilità, compie enormi donazioni di beneficienza a minuscole comunità in giro per il mondo e non si cura delle tendenze del mercato quando va contro i valori dietro al brand.", 
        punteggio: 5,
        src: "https://www.ibs.it/images/9788865492611_0_536_0_75.jpg",
        link: "https://www.amazon.it/people-surfing-filosofia-imprenditore-ribelle/dp/8865492619/ref=sr_1_1?keywords=let+my+people+go+surfing&qid=1666554869&qu=eyJxc2MiOiIxLjQ1IiwicXNhIjoiMS4wNiIsInFzcCI6IjEuMjAifQ%3D%3D&sprefix=let+my%2Caps%2C250&sr=8-1",
    },
    {
        titolo: "Fahreneith 451",
        citazione: "Un libro è una pistola carica.",
        recensione : "Che cosa succede se unite il significato politico di un libro e un scritto in stile 1984 alla George Orwell? Un romanzo ambientato in un futuro distopico che non ha nulla di invidiare al capolavoro di George Orwell ma che anzi, sotto certi punti di vista, ne è addirittura superiore. La trama dietro Fahreneit 451 è sicuramente meno romantica, ma allo stesso è più dinamica, incalzante e si concentra meno nella descrizione del regime totalitario sotto cui è ambientata la storia. Ne risulta una scrittura a cui è molto più facile farsi appassionare, la lettura scorre velocemente, nonostante il clima politico pesante caratteristico del romanzo e l'assurdità del contesto; ed è quasi esilerante per la presenza di situazioni tragi-comiche che spezzano la narrazione. ", 
        punteggio: 4,
        src: "https://upload.wikimedia.org/wikipedia/en/d/db/Fahrenheit_451_1st_ed_cover.jpg",
        link: "https://www.amazon.it/Fahrenheit-451-Ray-Bradbury/dp/8804665297/ref=sr_1_1?keywords=fahrenheit+451&qid=1666554880&qu=eyJxc2MiOiIxLjYwIiwicXNhIjoiMC45MiIsInFzcCI6IjAuOTIifQ%3D%3D&sprefix=fahren%2Caps%2C399&sr=8-1",
    },
    {
        titolo: "L'unica regola è che non ci sono regole",
        citazione: "Non c'è nessuna politica. Usa il buon senso. Agisci nell'interesse di Netflix.",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/41aRXSNYHJL.jpg",
        link: "",
    },
    {
        titolo: "Le tre del mattino",
        citazione: "Si è fatto tardi molto presto.",
        recensione : "", /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        punteggio: 4,
        src: "https://www.einaudi.it/content/uploads/2017/10/978880623607HIG.JPG",
        link: "https://www.amazon.it/tre-del-mattino-Gianrico-Carofiglio/dp/8806240706/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3IFRRP04A4TBT&keywords=le+tre+del+mattino&qid=1666554906&qu=eyJxc2MiOiIwLjQ1IiwicXNhIjoiMC4xNyIsInFzcCI6IjAuMjIifQ%3D%3D&sprefix=le+tre+del+matt%2Caps%2C295&sr=8-1",
    },
    {
        titolo: "New York è una città senza tende",
        citazione: "Qualcuno dice che siccome Manhattan è un isola, per continuare a vivere è costretta a demolire e ricostruire.",
        recensione : "Conosciamo tutti New York come la città dell'Empire State Building, ail toro di Wall Street, le meraviglie di Central Park e le opere d'arte del Moma. L'essenza della Grande Mela ci è tuttavia sconosciuta: Paolo Cognetti permette di conoscere i quartieri più iconici ma più estrani agli occhi dei turisti; rivelando una città ben diversa dagli stereotipi e molto più piena di contraddizioni di quanto sembri. Se siete già stati a New York questo libro è l'occasione per cambiare punto di vista verso la città; in caso contrario resterete ancora più incuriositi dalla città più amata e discussa al mondo.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788858130421_0_424_0_75.jpg",
        link: "https://www.amazon.it/New-York-finestra-senza-tende/dp/8858130421/ref=sr_1_1?keywords=new+york+%C3%A8+una+finestra+senza+tende&qid=1666554917&qu=eyJxc2MiOiIwLjI5IiwicXNhIjoiMC4wOCIsInFzcCI6IjAuMjMifQ%3D%3D&sprefix=new+york+%C3%A8%2Caps%2C231&sr=8-1",
    },
    {
        titolo: "The Hate u Give",
        citazione: "Thug Life stood for 'The Hate U Give Little Infants Fucks Everybody'",
        recensione : "Dopo l'omicidio di George Floyd del 2020 il movimento 'Black Lives Matter' ha guadagnato ancora più visibilità, per me il modo migliore per avvicinarsi a queste tematiche è stato leggere questo romanzo inverosimile, in cui l'oppressione razziale e i pregiudizi a cui sono ancora sottopostem molte persone di colore sono raccontati dal punto di vista di una giovane ragazza, talvolta incapace di comprendere e quasi ingenua di fronte alle situazioni paradossali che si trova ad affrontare per via delle sue origini. Leggere questo libro in lingua originale è stato sicuramente un valore aggiunto: mi ha permesso di immergermi, grazie allo 'slang' e ai modi di fare descritti; nella vita del protagonist e nel contesto sociale in cui è ambientato il romanzo.", 
        punteggio: 3,
        src: "https://www.ibs.it/images/9788809836402_0_536_0_75.jpg",
        link: "https://www.amazon.it/Hate-Give-coraggio-della-verit%C3%A0/dp/8809909909/ref=sr_1_1?keywords=the+hate+u+give&qid=1666554940&qu=eyJxc2MiOiIyLjQyIiwicXNhIjoiMi4wOSIsInFzcCI6IjIuMTIifQ%3D%3D&sprefix=the+hate%2Caps%2C634&sr=8-1",
    },
    {
        titolo: "After Dark",
        citazione: "La memoria umana è veramente strana: c'è conservata dentro un sacco di roba inutile, un sacco di cianfrusaglie.",
        recensione : "Definerei After Dark come il libro senza trama. Più di un romanzo si tratta infatti di una narrazione di situazioni, stati d'animo e relazioni tra i personaggi; non vi è infatti un filo conduttore logico che lega i capitoli del libro; ciò nonostante durante la lettura ci si immerge nell'ambientazione del libro che, per quanto possa sembrare surreale, è costruita a partire da un reale quartiere di Tokyo. Non vi aspettate di capire qualcosa o imparare nulla da questo libro, piuttosto divertevi e godetevi la lettura come se non dovesse restarvi nulla al termine del libro.",  
        punteggio: 3,
        src: "https://www.ibs.it/images/9788806217006_0_536_0_75.jpg",
        link: "https://www.amazon.it/After-dark-Haruki-Murakami/dp/8806217003/ref=sr_1_1?crid=2X4ISDSJZC33J&keywords=after+dark+murakami&qid=1666554955&qu=eyJxc2MiOiIwLjgwIiwicXNhIjoiMC41NyIsInFzcCI6IjAuNTEifQ%3D%3D&sprefix=after+da%2Caps%2C419&sr=8-1",
    },
    {
        titolo: "La mia vita per la libertà",
        citazione: "Voi occidentali, avete l'ora ma non avete mai il tempo.",
        recensione : "Ovviamente conoscevo Gandhi per la sua assoluta non-violenza; per cui, da amante delle storie di personaggi storici e di successo; mi sono immerso nella lettura dell'autobiografia del Mahatma: ho approfondito la sua ideologia e il contesto in cui si è ritrovato ad agire, felice tuttavia di essere in disaccordo riguardo tematiche e permettendomi di sviluppare meglio il mio punto di vista riguardo alcuni problemi sociali e politici del nostro tempo. Non si tratta nè di una lettura divertente nè facile, è tuttavia una buona occasione per imparare a sviluppare una propria mentalità e diventare più critici riguardo il mondo che ci circonda.", 
        punteggio: 3,
        src: "https://m.media-amazon.com/images/I/61SHXU6a9DL.jpg",
        link: "https://www.amazon.it/libert%C3%A0-Lautobiografia-profeta-della-non-violenza/dp/8854171654/ref=sr_1_1?keywords=la+mia+vita+per+la+libert%C3%A0&qid=1666554968&qu=eyJxc2MiOiIxLjA5IiwicXNhIjoiMC41OSIsInFzcCI6IjAuNzIifQ%3D%3D&sprefix=la+mia+vita+per+la+liber%2Caps%2C179&sr=8-1",
    },
    {
        titolo: "Il Potere delle Abitudini",
        citazione: "I campioni non fanno cose straordinarie. Fanno cose normali seguendo un abitudine.",
        recensione : "Sono abbastanza convinto che questo libro abbia rivoluzionata il modo di concepire e vivere la mia quotidianeità. Posso dire infatti che ormai svolgo la maggior parte delle mie attività per semplice abitudine. Per quanto possa sembrare monotono e noioso; essere delle persone guidate da solide routine comporta numerosi vantaggi: oltre a essere più efficienti e produttivi, permette di sprecare meno e fatica a decidere come e quando agire. Non vi garantisco che questo libro causerà gli stessi effetti  in voi, ma sicuramente cambierete idea riguardo il funzionamento del nostro corpo e leggerete numerosi consigli pratici su come implementare un'abitudine nella nostra quotidianeità.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/715dxFl2lSL.jpg",
        link: "https://www.amazon.it/potere-abitudini-formano-condizionano-cambiarle/dp/8850236905/ref=sr_1_1?keywords=il+potere+delle+abitudini&qid=1666554978&qu=eyJxc2MiOiIwLjgxIiwicXNhIjoiMC4zOSIsInFzcCI6IjAuMjgifQ%3D%3D&sprefix=il+potere+de%2Caps%2C184&sr=8-1",
    },
    {
        titolo: "Kafka sulla Spiaggia",
        citazione: "Poesia e simbolismo sono sempre stati inseparabili. Come i pirati e il rum.",
        recensione : "Non ricrdo molto dalla lettura di questo romanzo, se non che è stato il primo di Murakami e quello che mi ha fatto appasionare al modo di scrivere dell'autore giapponese. In 'kafka sulla spiaggia' il reale si confonde con l'immaginario, la vita quotidiana con il sogno, le azioni dei personaggi con i loro pensieri più intimi; fino a creare una condizione surreale in cui immergersi e di cui, almeno inizialmente, si capisce ben poco. E' questo tuttavia il punto forte di questo libro: aspettatevi tutto il contrario di una trama lineare, personaggi razionali e una narrazione logica e verosimile: nulla infatti si può dare per certo durante la lettura del romanzo.", 
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/61R0XpGhHgL.jpg",
        link: "https://www.amazon.it/Kafka-sulla-spiaggia-Haruki-Murakami/dp/8806216945/ref=sr_1_1?keywords=kafka+sulla+spiaggia+murakami&qid=1666554989&qu=eyJxc2MiOiIwLjk3IiwicXNhIjoiMC41MSIsInFzcCI6IjAuNDAifQ%3D%3D&sprefix=kafka+sulla%2Caps%2C209&sr=8-1",
    },
    {
        titolo: "L'ordine del Tempo",
        citazione: "Il tempo passa più velocemente in montagna che in collina.",
        recensione : "Ho letto questo libro tre volte e sono convinto di non averne ancora compreso a pieno il contenuto, sono certo tuttavia che la mia concezione dello 'scorrere del tempo' sia stata completamente rivoluzionata. Che voi siate degli appassionati di fisica o meno e a prescindere di quanto capirete delle parti più tecniche del testo di Rovelli, scoprirete alcune verità sulla fisica che, nonostante non abbiano alcuna applicazione nel quotidiano; conferiranno una maggiore comprensione di come, in maniera del tutto controintuivia e inaspettata, funziona il mondo in cui viviamo.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71GL+ee5ddL.jpg",
        link: "https://www.amazon.it/Lordine-del-tempo-Carlo-Rovelli/dp/8845931927/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3AKZZF3K9NAAY&keywords=l%27ordine+del+tempo&qid=1666555000&qu=eyJxc2MiOiIwLjQ3IiwicXNhIjoiMC4zMCIsInFzcCI6IjAuMjQifQ%3D%3D&sprefix=l+ordine+del+tem%2Caps%2C205&sr=8-1",
    },
    {
        titolo: "Il Nome della Rosa",
        citazione: "Spesso sono gli inquisitori a creare gli eretici.",
        recensione : "Leggere il capolavoro di Umberto Eco ha suscitato in me sensazioni contrastanti: la trama intrigante e incalzante mi motivava a perseguire nella lettura, l'ambientazione, un monastero benettino isolato dalla società, così lontana e inimmaginabile per un ragazzo del terzo millenio mi incuriosiva; mentre le interminabili e dettagliatissime descrizioni di ogni cosa, persona o avvenimento menzionata nel romanzo tendevano ad annoiarmi e a farmi leggere con distrazione quelle parti di libro. IL problema di questo film è rappresentato tuttavia dall'omonimo film, realizzato con estrema cura dei particolari e con fedeltà rispetto al testo: vi è infatti il rischio che il lettore si lasci 'impigrire' dalla lunghezza del libro in favore di una 'più' facile e leggera visione della pellicola.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/81dhmnbA1VL.jpg",
        link: "https://www.amazon.it/nome-della-rosa-Ediz-illustrata/dp/8834603001/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1LVL1YP35Z1LT&keywords=il+nome+della+rosa&qid=1666555010&qu=eyJxc2MiOiIyLjIxIiwicXNhIjoiMS4yNyIsInFzcCI6IjEuMTcifQ%3D%3D&sprefix=il+nome+della+ro%2Caps%2C190&sr=8-1",
    },
    {
        titolo: "L'estate che conobbi il Che",
        citazione: "«Ma cosa c’entra la scuola con la rivoluzione?» «Cesare, la rivoluzione si fa con le idee, non con i fucili».",
        recensione : "Come fa il Che Guevara a entrare in modo definitivo nella vita di Cesare, un tipico ragazzo brianzolo poco interessato di politica e storia? Garlando, come già dimostrato nei suoi precedenti romanzi, riesce a raccontare la storia di grandi personaggi storici lontanissimi geograficamente e cronologicamente 'trasportandoli' in un contesto a noi molto più vicino. Le storie dei due protagonisti infatti, il Che e Cesare, si intrecciano, inizialmente quasi per caso; dando vita a una narrazione che viaggia nel tempo restando tuttavia connessa con la vita 'mondana' del adolescente protagonista che, nel frattempo, ha l'occasione di scoprire molto diù riguardo la sua famiglia e crescere dal punto di vista personale.", 
        punteggio: 4,
        src: "https://www.rizzolilibri.it/content/uploads/2015/04/17/278764/3253969-9788817080040.png",
        link: "https://www.amazon.it/Lestate-che-conobbi-Luigi-Garlando/dp/8817096466/ref=sr_1_1?keywords=l+estate+che+conobbi+il+che&qid=1666555026&qu=eyJxc2MiOiIwLjc2IiwicXNhIjoiMC40MiIsInFzcCI6IjAuMjYifQ%3D%3D&sprefix=l%27estate+che+conob%2Caps%2C183&sr=8-1",
    },
    {
        titolo: "La sottile arte di fare quello che cazzo ti pare",
        citazione: "La società confonde l'attenzione con il successo. Il semplice fatto di poter scegliere i valori per cui sbatterci ci rende persone di successo.",
        recensione : "Il titolo del libro potrebbe essere frainteso per il tono utilizzato, eppure l'autore invita veramente a fare 'quel cazzo che vogliamo'; ossia di conferire molta meno importanza a tutte le aspettative della società e impegnare il nostro tempo in ciò che veramente da valore alle nostre vite. La chiave per essere felici e soddisfatti delle proprie giornte è rappresentata da questo: essere estreamemnte selettivi su ciò per cui decidiamo di sbatterci; uscendo completamente dalla mentalità che ci spinge a fare sempre di più e limitando le nostre attività a ciò in cui crediamo realmente. ", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788822707475_0_536_0_75.jpg",
        link: "https://www.amazon.it/scorretto-efficace-liberarsi-irritanti-problemi/dp/8822707451/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=",
    },
    




]
