
module.exports = [
    {
        titolo: "Kitchen Confidential",
        citazione: "Mi piace pensare che la cucina sia un'arte e un buon cuoco sia un artigiano.",
        recensione: "Al giorno d’oggi, agli chef stellati sono riservate attenzioni e reputazione che prima spettavano ad attori famosi, vincenti sportivi e famosi uomini dello spettacolo; Bourdain tuttavia, attraverso la sua autobiografia composta da momenti di crisi personali, difficoltà lavorative e problematiche relazionali, svela i retroscena e i segreti meno dicibili della carriera da cuoco, mettendone in luce le grandi fatiche, i sacrifici necessari e l’ambiente corrotto, meschino ed estremamente aggressivo che si nasconde dietro le porte delle grandi cucine. Nel libro sono inoltre presenti numerosi dettagli e aneddoti sul settore, tra cui non mancano anche alcuni consigli su come comportarsi al ristorante e qualche suggerimento per accrescere le proprie abilità in cucina.",
        punteggio: 3,
        src: "https://m.media-amazon.com/images/I/51h+XSRw5dL._SX323_BO1,204,203,200_.jpg",
        link: "https://www.amazon.it/Kitchen-confidential-Avventure-gastronomiche-York/dp/8807880296/ref=asc_df_8807880296/?tag=googshopit-21&linkCode=df0&hvadid=194921532888&hvpos=&hvnetw=g&hvrand=17872928403621149485&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1008463&hvtargid=pla-82819613820&psc=1",
    },
    {
        titolo: "The Way of the runner",
        citazione: "The purpose of training is not health or strenght, but forging the soul",
        recensione: "Il Giappone ha sempre mostrato grandi differenze dal mondo occidentale, in tutti gli ambiti della vita; nel running queste differenze culturali sono portate all'estremo.  Nella terra del Sol Levante infatti, la corsa è uno degli sport più amati e seguiti in TV, i ragazzi frequentano team scolastici di atletica fin dall’infanzia e le gare a staffetta sulle lunghe distanze, i cosiddetti ekiden, sono considerati gli eventi dell'anno. Eppure, tra tutti i campioni olimpici del fondo e del mezzofondo raramente spicca un orientale. L'autore del libro, un runner inglese che ha iniziato ad allenarsi seguendo le metodologie e i ritmi giapponesi, cerca di risolvere questo mistero scoprendo le passioni, le motivazioni e le contraddizioni del fenomeno sociale dell’atletica in Giappone.",
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/812l4+GDnCL.jpg",
        link: "https://www.amazon.it/Way-Runner-journey-Japanese-running-ebook/dp/B00SEU8848",
    },
    {
        titolo: "The Rise of Ultrarunner",
        citazione: "'Why do you run?' 'It's the closest thing to flying'",
        recensione: "Le maratone non sono più abbastanza, la nuova frontiera del running verte sul correre per ore, se non giorni, in condizioni ambientali e climatiche avverse, 'solamente' per ottenere piacere e soddisfazione personale.   Che cosa spinge questi atleti a massacrare il proprio corpo per raggiungere questa forma di realizzazione? Che cosa motiva una persona a correre centinaia di chilometri a settimana o a compiere il giro del Monte Bianco sulle proprie gambe in meno di un giorno? L'autore del libro, per cercare di comprenderlo, si è messo nei panni di uno di loro iniziando a praticare questo sport con l’obiettivo di partecipare alle gare di ultrarunning più celebri, oltre a intervistare gli sportivi più esperti in questo mondo e a raccontare la loro esperienza. Adharanand Finn offre dei pratici consigli per chi desidera avvicinarsi a questo mondo o semplicemente vuole iniziare a correre.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/91rPEgbBOqL.jpg",
        link: "https://www.amazon.it/Rise-Ultra-Runners-Journey-Endurance/dp/1643135996",
    },
    {
        titolo: "Tu non sai cos'è la guerra",
        citazione: "Mi vergogno ad ammettere di non avere una casa... L'ho sempre trovato insopportabile, dal giorno in cui siamo fuggite.",
        recensione: "Da quando è iniziata la guerra in Ucraina siamo bombardati da tragiche notizie provenienti dall'est europa. Tuttavia, spesso manca il punto di vista di una gran parte della popolazione coinvolta, quello dei bambini. La giovanissima autrice di questo libro, una dodicenne ucraina costretta a scappare dalla propria città a causa degli attacchi russi, racconta ciò che comporta la guerra nel quotidiano per la maggior parte della popolazione: mancanza di cibo, acqua e medicinali, lontananza da casa e dai parenti, ma soprattutto la semplice normalità ormai andata persa. Tutto ciò che fino a poco prima dello scoppio del conflitto era dato per scontato, ora appare come un sogno che non potrà mai più avverarsi. ", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9791221203134_0_536_0_75.jpg",
        link: "https://www.amazon.it/Tu-non-sai-cosè-guerra-ebook/dp/B0BHX12FJZ",
    },
    {
        titolo: "California",
        citazione: "Insomma, vorremmo essere un po' più come la California, che infatti da secoli è considerata la «fine del mondo»",
        recensione: "Immaginiamo tutti la California come la terra dei sogni dove vigneti paradisiaci incontrano il surf di Malibu Beach e le celebrità di Hollywood si confondono con gli imprenditori che progettano applicazioni e tecnologie che governano la vita di tutto il mondo. Eppure, Francesco Costa racconta come la California stia attraversando una grande crisi sociale ed economica e individua la responsabilità di questo declino ai californiani stessi, incapaci di accettare i cambiamenti e troppo bramosi di mantenere lo status quo. Secondo l’autore, questa crisi non riguarda solamente il Golden State, ma sta attraversando molte altre realtà sociali che stanno andando nella stessa direzione. Costa espone le soluzioni attuabili per non replicare i drammatici fatti accaduti nello stato americano.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/71jll4IJAmL.jpg",
        link: "https://www.amazon.it/California-Francesco-Costa/dp/8804755210/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3VXSC7PW0ZB64&keywords=california+costa&qid=1666554573&qu=eyJxc2MiOiIwLjEyIiwicXNhIjoiMC4wNiIsInFzcCI6IjAuMTAifQ%3D%3D&sprefix=california+cost%2Caps%2C193&sr=8-1",
    },
    {
        titolo: "What I learned losing a million dollars",
        citazione: "You don't know why the market is going up or down, you just want to know what is doing",
        recensione : "Imparare dai propri insuccessi è la prima regola nell'imprenditoria moderna, eppure è sempre la pratica più difficile da attuare quando si tratta di affrontare un fallimento, soprattutto nel trading dove ogni giorno milioni di persone scommettono i propri soldi senza un approccio razionale e una conoscenza approfondita del settore. L'autore parte proprio dalla sua esperienza di trader inesperto, ma fortunato, che a lungo ha attribuito il merito dei suoi guadagni alle sue abilità e non alla fortuna e finendo sulla strada della rovina.   Nel libro viene descritta e analizzata la tipica mentalità americana legata al business, ma non mancano aneddoti personali, storie di imprenditoria e commercio, nonchè concetti più teorici legati ai bias mentali che ci conducono verso certi comportamenti errati negli investimenti.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51fGOyjVMlL.jpg",
        link: "https://www.amazon.it/What-Learned-Losing-Million-Dollars/dp/0231164688/ref=sr_1_1?keywords=what+i+learned+losing+a+million+dollars&qid=1666554557&qu=eyJxc2MiOiIwLjQ4IiwicXNhIjoiMC4xMSIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=what+i+learn%2Caps%2C217&sr=8-1",
    },
    {
        titolo: "Antifragile",
        citazione: "E' fragile ciò che subisce perdite nell'incertezza. E' antifragile tutto il contrario.",
        recensione : "Siamo tutti convinti che il contrario di fragile sia robusto, tuttavia nessuno hai mai dato rilevanza al concetto di antifragililità, ossia all'abilità di rafforzarsi nelle difficoltà e nella volatilità, concetto a cui l’economista Taleb conferisce molta importanza e attenzione.   Partendo dal presupposto che non è possibile prevedere e proteggersi dai rischi e dagli imprevisti del mondo con certezza, diventa dunque preferibile imparare a trarre vantaggio dal disordine e dagli errori. Facendo ciò, si cambia completamente il paradigma delle proprie azioni e si adotta un approccio più empirico, spontaneo e più diffidente nei confronti degli studi teorici sulla probabilità, studi su cui la società odierna troppo spesso si basa.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/71ly-xl-lnL.jpg",
        link: "https://www.amazon.it/Antifragile-Prosperare-disordine-Nassim-Nicholas/dp/8842819174/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1QVIMKQL0KLRP&keywords=antifragile&qid=1666554598&qu=eyJxc2MiOiIxLjA1IiwicXNhIjoiMC44MyIsInFzcCI6IjAuOTkifQ%3D%3D&sprefix=antifragile%2Caps%2C192&sr=8-1",
    },
    {
        titolo: "L'Arte dell'hacking",
        citazione: "Dal mio punto di vista, l'hacking è una pratica creativa come l'arte.",
        recensione : "Gli hacker al giorno d'oggi sono visti come geniali informatici che decidono di sfruttare le loro competenze per craccare software, violare la privacy e rubare soldi e dati. Eppure dietro queste figure nate con l'avvento dell'informatica moderna si nasconde molto di più. Un hacker infatti, non è altro che una persona curiosa delle fallacie del sistema e che di conseguenza prova a trarre vantaggio da queste sue conoscenze. Quest'attitudine può portare su strade diverse a seconda dell’etica dell’informatico: dall'impiego nella pubblica amministrazione, allo spionaggio militare, alla gestione di dati in società o banche private o, come nella maggior parte dei casi, per puro e sano divertimento.",
        punteggio: 4,
        src: "https://www.ibs.it/images/9788807883606_0_424_0_75.jpg",
        link: "https://www.amazon.it/Larte-dellhacking-Kevin-D-Mitnick/dp/8807883600/ref=sr_1_2?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2QEEYB59UIJYM&keywords=l%27arte+dell%27hacking&qid=1666554610&qu=eyJxc2MiOiIxLjc5IiwicXNhIjoiMS44NiIsInFzcCI6IjEuNjEifQ%3D%3D&sprefix=l+arte+dell+hacking%2Caps%2C187&sr=8-2",
    },
    {
        titolo: "Ovunque",
        citazione: "Quando viaggio da solo mi passa la voglia di cambiarmi, tanto a chi posso dar fastidio?",
        recensione : "Niccolò Balinì, meglio conosciuto su YouTube come Human Safari, in questo libro racconta, in modo molto 'leggero e chiacchierato', le sue improbabili avventure in giro per il mondo nel periodo in cui la possibilità di viaggiare si è ridotta drasticamente: gli anni del Covid.   Il mezzo di trasporto protagonista, anche viste le complicazioni legate alla pandemia, è la vespa a bordo della quale Niccolò ha viaggiato attraversando tutta la penisola italiana e spingendosi oltre i confini nazionali. Per quanto si riconosca che il libro sia scritto da ‘uno youtuber', si tratta di cronache perfette per una lettura serale e disimpegnata che invita a lasciarci alle spalle le nostre quotidianità per viaggiare senza una meta precisa e senza troppe pretese, apprezzando ciò che i luoghi visitati offrono e adattandosi alle condizioni di viaggio.",
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51xdROB0qnL.jpg",
        link: "https://www.amazon.it/Ovunque-Nicol%C3%B2-Balini/dp/8820073072/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=XQMLE4BQPBCJ&keywords=ovunque&qid=1666554620&qu=eyJxc2MiOiIxLjE1IiwicXNhIjoiMC44NyIsInFzcCI6IjEuMzIifQ%3D%3D&sprefix=ovunqu%2Caps%2C190&sr=8-1",
    },
    {
        titolo: "La Traiettoria",
        citazione: "Vengo da una famiglia dove seguire le regole è un imperativo. Per capire chi ero ho dovuto infrangerle",
        recensione : "Il cognome Benetton non ha bisogno di presentazioni, eppure dietro Alessandro Benetton, figlio di Luciano, fondatore dell’omonimo brand di abbigliamento e del grande gruppo industriale italiano, si cela una storia fatta di imprevisti, di scelte controverse in opposizione alla famiglia e di una grande voglia di intraprendere una propria strada, indipendentemente dalle aspettative e dalle volontà della famiglia. L’esperienza di Alessandro suggerisce quindi di assumersi le proprie responsabilità, di percorrere la propria vita indipendentemente dalle aspettative sociali e di rompere le regole, qualora questa rottura fosse necessaria per raggiungere un fine ultimo personale più importante.",
        punteggio: 4,
        src: "https://www.ibs.it/images/9788804749080_0_536_0_75.jpg",
        link: "https://www.amazon.it/traiettoria-Alessandro-Benetton/dp/8804749083/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=364VA79PM5XO9&keywords=la+traiettoria&qid=1666554636&qu=eyJxc2MiOiIwLjE5IiwicXNhIjoiMC4xMSIsInFzcCI6IjAuMjMifQ%3D%3D&sprefix=la+traiettori%2Caps%2C179&sr=8-1",
    },
    {
        titolo: "Giocati dal Caso",
        citazione: "Nessuno accetta il caso come causa del proprio successo, ma solo del proprio fallimento.",
        recensione : "Nella nostra vita di tutti i giorni, siamo così impegnati a pianificare, prevedere e calcolare che diamo poca importanza a ciò che governa le nostre vite: il caso. Un minimo cambiamento può causare conseguenze gigantesche nelle nostre vite e il concetto di probabilità matematica, così come lo abbiamo conosciuto fino ad ora, diventa inutile per trarre vantaggi dalla volatilità. Taleb, pur essendo un esperto matematico e di economia, non apprezza inutili studi accademici puramente teorici e invita ad assumere un approccio più empirista, a non confondere le nostre abilità con il caso e a distinguere causalità e casualità.", 
        punteggio: 4,
        src: "https://kbimages1-a.akamaihd.net/07db90c8-5875-48b7-86a0-7d73423973a5/1200/1200/False/giocati-dal-caso-1.jpg",
        link: "https://www.amazon.it/Giocati-caso-ruolo-fortuna-finanza/dp/8842820237/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2C07373FYB580&keywords=giocati+dal+caso&qid=1666554645&qu=eyJxc2MiOiIwLjcwIiwicXNhIjoiMC41MiIsInFzcCI6IjAuMzUifQ%3D%3D&sprefix=giocati+dal+cas%2Caps%2C171&sr=8-1",
    },
    {
        titolo: "CARCHITECTURE - Houses with horsepower",
        citazione: "Homes should be built in factories similar to those for automobiles",
        recensione : "Che cosa c'entra Le Corbusier con l'azienda automobilistica SAAB?     CARCHITECTURE non cerca di rispondere a questa domanda in modo approfondito e tecnico, eppure riesce a mettere a confronto due mondi che spesso non sono mai accostati: l'architettura e le automobili. Non aspettatevi però un'analisi approfondita del rapporto tra questi due mondi, prendete il libro per quello che è: una semplice, ma piacevole raccolta di scatti che ritraggono architetture e macchine che, per la loro storia, per il loro stile o semplicemente per i loro proprietari, sono collegati.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/41SfoJBKnNL.jpg",
        link: "https://www.amazon.it/Carchitecture-Houses-Horsepower-Thijs-Demeulemeester/dp/9401461031",
    },
    {
        titolo: "Steve Jobs non abita qui",
        citazione: "Airbnb non è proprio come McDonald's, ma come un avocato toast sostenibile e facilmente replicabile.",
        recensione : "La Silicon Valley viene spesso descritta come il posto di lavoro da sogno, in particolare per tutti i giovani appassionati di innovazione e tecnologia che ogni anno si spingono fino a Los Angeles, San Francisco e Cupertino in cerca del sogno americano. Eppure non è tutto oro quel che luccica. Dietro la California da sogno si cela anche la sua controparte più corrotta, faticosa e illusa di essere sempre nel giusto. Michele Masneri compone un ritratto ironico e inusuale di questa regione che ormai è diventata un vero e proprio status symbol e rappresenta uno stile di vita invidiato (inspiegabilmente...?) da tutto il mondo.", 
        punteggio: 5,
        src: "https://www.adelphi.it/spool/cover__id8866_w600_t1594807353.jpg&.jpg",
        link: "https://www.amazon.it/Steve-Jobs-non-abita-pi%C3%B9/dp/8845934640/ref=sr_1_1?keywords=steve+jobs+non+abita+pi%C3%B9+qui&qid=1666554659&qu=eyJxc2MiOiIwLjM5IiwicXNhIjoiMC4yMyIsInFzcCI6IjAuMjEifQ%3D%3D&sprefix=steve+j%2Caps%2C178&sr=8-1",
    },
    {
        titolo: "La vera storia del genio che ha fondato McDonald",
        citazione: "Credo in Dio, nella famiglia e in McDonald’s - in ufficio, però, l’ordine va invertito.",
        recensione : "Se ci si vuole immergere nella testa di uno degli imprenditori più americani di sempre si tratta del libro giusto. Ray Kroc incarna infatti, lo stereotipo dell'uomo d'affari che, cogliendo ogni buona opportunità che gli si presenta, è riuscito a trasformare un semplice chiosco di 'burger and fries' nella catena di fast food più diffusa al mondo. Oltre a essere fonte di ispirazione per chi è motivato a costruire qualcosa di proprio, il libro affronta in modo pratico i problemi a cui si va in contro in termini di prodotto, gestione del personale, rapporto con il cliente e con i fornitori quando si tratta di gestire un business come McDonald's che, pur essendo diffuso globalmente, rispecchia ancora oggi i valori del suo fondatore.",
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/41PADEM8WzL.jpg",
        link: "https://www.amazon.it/vera-storia-genio-fondato-McDonalds%C2%AE/dp/B07D4ZPJL9/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1UM8TB4N0M2FL&keywords=la+vera+storia+del+genio&qid=1666554671&qu=eyJxc2MiOiIwLjc4IiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=la+vera+storia+del+genio%2Caps%2C191&sr=8-1",
    },
    {
        titolo: "Helgoland",
        citazione: "La teoria dei quanti è la migliore descrizione della natura di cui disponiamo oggi.",
        recensione : "Se qualcuno dichiara di comprendere appieno la fisica quantistica significa che chi gliel'ha spiegata non si è espresso bene. Questo concetto viene più volte ribadito nel libro dall'autore per sottolineare quanto sia controintuitiva e difficile questa branca della scienza. Carlo Rovelli tuttavia, è in grado di accennarne i concetti fondamentali, a differenza de 'L'Ordine del Tempo' tuttavia, sono richieste alcune conoscenze pregresse e un’elasticità mentale abbastanza avvezza al linguaggio scientifico per comprendere i punti chiave della meccanica quantistica. Pur essendo molto complicato nei concetti; il libro utilizza un linguaggio semplice e ricorre al racconto di divertenti aneddoti storici che ne facilitano la comprensione.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/617aCsvbXJL.jpg",
        link: "https://www.amazon.it/Helgoland-Carlo-Rovelli/dp/8845935051/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=BWGZ49K45D8E&keywords=helgoland&qid=1666554692&qu=eyJxc2MiOiIwLjkzIiwicXNhIjoiMC40NCIsInFzcCI6IjAuNDEifQ%3D%3D&sprefix=halgola%2Caps%2C224&sr=8-1",
    },
    {
        titolo: "Una Terra Promessa",
        citazione: "Ero diventato un politico. E nemmeno troppo bravo.",
        recensione : "L'ex Presidente degli Stati Uniti, ormai lontano dal potere politico, riesce a raccontare intimamente e sinceramente il percorso che lo ha portato alla Casa Bianca e gli anni trascorsi alla guida degli USA. Pur concentrandosi sui suoi anni di Governo, non mancano le vicende legate alla giovinezza e alle scelte che lo hanno condotto fino alle primarie del Partito Democratico, ma per una lettore non americano, questi capitoli del libro risultati meno densi di valore e talvolta quasi noiosi.     Le riflessioni sul suo periodo di presidenza offrono invece diversi spunti, sia per tutte le volte in cui l'autore compie un passo indietro rispetto alle sue decisioni passate sia per tutti i momenti in cui le scelte e i progetti di un solo uomo hanno determinato grandi conseguenze a livello internazionale.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71W0kAoWW4L.jpg",
        link: "https://www.amazon.it/Una-terra-promessa-Barack-Obama/dp/8811149878/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2VVVS5PA89EES&keywords=una+terra+promessa&qid=1666554702&qu=eyJxc2MiOiIxLjkwIiwicXNhIjoiMS42NCIsInFzcCI6IjAuNTcifQ%3D%3D&sprefix=una+terra+promess%2Caps%2C237&sr=8-1",
    },
    {
        titolo: "Corro perchè mia madre mi picchia",
        citazione: "La corsa è inutile, e proprio per questo va coltivata. Come un'arte.",
        recensione : "Essendo sia milanese che corridore come gli autori, dovevo assolutamente leggere questo libro e, proprio come mi aspettavo, la sua lettura non ha fatto altro che motivarmi e divertirmi. Così come avrebbero fatto tutti gli altri runner, mi sono completamente ritrovato e immedesimato in ogni vicenda, abitudine e pensiero narrato all'interno del libro.   Se anche voi siete dei corridori, questo libro potrebbe essere un titolo perfetto per una lettura disimpegnata, leggera, ma molto divertente; se invece non siete molto affini ad indossare delle scarpe da atletica, nonostante il libro non contenga molti consigli pratici su come avvicinarsi a questo sport, potrebbe darvi la motivazione per correre i primi chilometri.", 
        punteggio: 4,
        src: "https://www.oscarmondadori.it/content/uploads/2017/08/978880464855HIG.JPG",
        link: "https://www.amazon.it/Una-terra-promessa-Barack-Obama/dp/8811149878/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2VVVS5PA89EES&keywords=una+terra+promessa&qid=1666554702&qu=eyJxc2MiOiIxLjkwIiwicXNhIjoiMS42NCIsInFzcCI6IjAuNTcifQ%3D%3D&sprefix=una+terra+promess%2Caps%2C237&sr=8-1",
    },
    {
        titolo: "Una notte ho sognato New York",
        citazione: "Bastano cinque minuti per sentirti parte di New York, ma una vita intera per capirla fino in fondo",
        recensione : "Piero Armenti, italiano trasferitosi nella Grande Mela dove ha avviato un'agenzia viaggi di successo, in questo romanzo verosimile racconta la storia di uno dei tanti italiani fissati con il sogno americano. Il desiderio di vivere e lavorare negli States, che anche l’autore ha vissuto in età giovanile, viene approfondito al meglio descrivendo tutte le contraddizioni, i lati positivi e le fatiche che si celano dietro la vita sognata da migliaia di emigrati ogni anno. Il lettore può immedesimarsi nei progetti e nelle speranze di chi, per scelta o quasi per caso, è costretto a combattere ogni giorno per sopravvivere a New York per guadagnare un posto di lavoro stabile e continuativo nel proprio territorio dei sogni.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61vKCnaTK8L.jpg",
        link: "https://www.amazon.it/Una-notte-sognato-New-York/dp/8804724994/ref=sr_1_1?keywords=una+notte+ho+sognato+new+york&qid=1666554723&qu=eyJxc2MiOiIxLjA1IiwicXNhIjoiMC43MyIsInFzcCI6IjAuNzUifQ%3D%3D&sprefix=una+notte+h%2Caps%2C202&sr=8-1",
    },
    {
        titolo: "I Principi del Successo",
        citazione: "Confidate nella verità a tutti i costi e nella trasparenza estrema",
        recensione : "Ray Dalio è uno degli investitori più di successo degli ultimi anni, eppure i principi alla base degli alti rendimenti del suo fondo di investimento, Bridgewater associates, possono essere applicati a ogni aspetto della nostra vita. Il metodo di Ray Dalio infatti presuppone che, invece che agire sulla base di regole specifiche per ogni situazione, si costruisca un 'sistema' di valori e procedure da poter applicare a ogni ambito di lavoro. Oltre a formare una determinata 'forma mentis' interdisciplinare, l'autore insegna ad analizzare il ruolo della ciclicità in ogni fenomeno: per imparare al meglio dal passato è necessario saper applicare e confrontare pattern già avvenuti per comprendere in che fase di un determinato periodo storico ci si trovi.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71LyvaUH80L.jpg",
        link: "https://www.amazon.it/principi-del-successo-Ray-Dalio/dp/8820385716/ref=sr_1_1?keywords=i+principi+del+successo+ray+dalio&qid=1666554733&qu=eyJxc2MiOiIxLjI4IiwicXNhIjoiMC44MSIsInFzcCI6IjAuOTEifQ%3D%3D&sprefix=i+principi+del+%2Caps%2C208&sr=8-1",
    },
    {
        titolo: "Il Cigno Nero",
        citazione: "Perchè ci ostiniamo a pianificare il futuro quando le nostre vite vengono modificate dall'ignoto?",
        recensione : "Un Cigno Nero non è altro che un evento unico, raro, inspiegabile a priori e che che genera un impatto enorme sulla società. Secondo Taleb sono questi fatti a governare la realtà in cui viviamo e, a causa della loro estrema indeterminatezza; tutti gli studi probabilistici e legati al rischio diventano inutili. Lo scrittore consiglia quindi di cambiare totalmente prospettiva: piuttosto che cercare di prevedere questi episodi; è meglio mettersi in una posizione in modo da poter trarre vantaggi dall'alta volalitità in cui siamo immersi. Applicare queste strategie nella vita quotidiana, eppure l'esperienza di Taleb dimostr che, soprattutto in ambito finanziario e lavorativo; la volatilità e i cambiamenti inaspettati e repentini possono portare numerosi vantaggi se affrontati correttamente.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61rsVxQlXIL.jpg",
        link: "https://www.amazon.it/cigno-nero-limprobabile-governa-nostra/dp/884282027X/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2HWYIG0PARQ2W&keywords=il+cigno+nero&qid=1666554745&qu=eyJxc2MiOiIwLjc5IiwicXNhIjoiMC40MiIsInFzcCI6IjAuNTAifQ%3D%3D&sprefix=il+cigno+ne%2Caps%2C177&sr=8-1",
    },
    {
        titolo: "La mucca viola",
        citazione: "O sei una mucca viola o non sei nessuno. O sei straordinario o non esisti.",
        recensione : "Il titolo potrebbe trarre in inganno i possibili lettori riguardo il contenuto; questo libro infatti, nonostante non sia propriamente un saggio specifico dato che utilizza un linguaggio e una narrazione accessibile a tutti, sintetizza in maniera abbastanza esaustiva e sintetica tutti i principi che dovrebbero stare alla base di un'operazione marketing di successo. Oltre a spiegazioni più teoriche, sono proposti numerosi case studies fallimentari e di successo che rappresentano le debolezze o i punti di forza di differenti modi di concepire e progettare la pubblicità.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/718OGpfUOMS.jpg",
        link: "https://www.amazon.it/mucca-viola-notare-fortuna-marrone/dp/8836200559/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1QD6TIK1V14XD&keywords=la+mucca+viola&qid=1666554757&qu=eyJxc2MiOiIxLjExIiwicXNhIjoiMC40MyIsInFzcCI6IjAuMzUifQ%3D%3D&sprefix=la+mucca+viol%2Caps%2C154&sr=8-1",
    },
    {
        titolo: "La montagna dentro",
        citazione: "Appendo l'amaca. Sotto di me il vuoto, sopra di me le stelle.",
        recensione : "Nonostante pochi conoscano Herve Barmasse, l'autore di questo libro è un alpinista e scrittore molto conosciuto e rispettato da tutti gli amanti della montagna.  Raccontando alcune sue vicende autobiografiche, Barmasse riesce a descrivere il suo rapporto fortissimo con la montagna e la società in cui vive, offrendo inoltre numerose lezioni sul corretto modo di vivere il mondo dell'alpinismo. Nel libro non sono presenti consigli tecnici su come avvicinarsi allo sci di fondo o all'arrampicata, ma sicuramente vi verrà voglia di lasciare la città e di esplorare ad alta quota, a prescindere dal vostro livello tecnico e da quanto siete allenati.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788858130117_0_536_0_75.jpg",
        link: "https://www.amazon.it/montagna-dentro-Herv%C3%A9-Barmasse/dp/8858130111/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=OGPON7MJPART&keywords=la+montagna+dentro&qid=1666554768&qu=eyJxc2MiOiIxLjE4IiwicXNhIjoiMC42MiIsInFzcCI6IjAuNTYifQ%3D%3D&sprefix=la+montagna+dent%2Caps%2C160&sr=8-1",
    },
    {
        titolo: "Allegro Occidentale",
        citazione: "....E scoprì che i cinesi vedono gli occidentali tutti allo stesso modo.",
        recensione : "Il modo in cui noi occidentali viaggiamo è del tutto tragi-comico. Ce lo insegna Francesco Piccolo con questo breve, esilarante e divertente romanzo in cui viene raccontato il viaggio di un gruppo di benestanti e 'ingenui' europei alla scoperta di un mondo che è ben diverso da come se lo immaginavano. Assumendo un punto di vista differente, comprendiamo infatti che la maggior parte delle volte in cui visitiamo un posto nuovo stiamo vedendo solamente quello che ci aspettiamo di trovare, non ciò che quella località è davvero, come se le nostre aspettative verso un contesto lontanissimo da noi dovessero necessariamente rispecchiare l'autenticità del luogo.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61H+Jg0kL+L.jpg",
        link: "https://www.amazon.it/Allegro-occidentale-Francesco-Piccolo/dp/8806227599/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2W7YH4X10OS88&keywords=allegro+occidentale&qid=1666554781&qu=eyJxc2MiOiIwLjAwIiwicXNhIjoiMC4wMCIsInFzcCI6IjAuMDAifQ%3D%3D&sprefix=allegro+occidental%2Caps%2C176&sr=8-1il ",
    },
    {
        titolo: "Il metodo Warren Buffet",
        citazione: "Ciò che mi preoccupa di più è la mcnanza di fiducia negli investimenti a lungo termine.",
        recensione : "Il libro, considerato da tutti il Sacro Graal della letteratura finanziaria, attraverso il racconto della vita di Buffet, descrive la sua vincente strategia di investimento. Le metodologie presentate nel libro non sono tuttavia spendili da tutti nel breve periodo, ma leggendolo si può cambiare il punto di vista verso questo settore, assumendo una mentalità molto più saggia, improntata sul lungo termine, sul valore di un'azienda e sull'investire su ciò che realmente si conosce. Gli investimenti di Buffet prevedono infatti, un orizzonte di tempo spesso superiore al decennio, si concentrano esclusivamente sulle aziende il cui business model sia facilmente comprensibile e sono sempre il risultato di un'analisi razionale e basata sul presente e su una conoscenza approfondita del settore.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/51q-meCl8VL.jpg",
        link: "https://www.amazon.it/metodo-Warren-Buffett-segreti-investitore/dp/8820362716/ref=sr_1_1?keywords=il+metodo+warren+buffett&qid=1666554796&qu=eyJxc2MiOiIxLjQ0IiwicXNhIjoiMC44NyIsInFzcCI6IjAuNjgifQ%3D%3D&sprefix=il+metodo+w%2Caps%2C160&sr=8-1",
    },  
    {
        titolo: "Homo Sapiens",
        citazione: "Siamo dei che si sono fatti da sè.",
        recensione : "Il sottotitolo di questo libro è 'Breve Storia dell'Umanità', ciò nonostante non si pensi che il libro si concentri sul passato della nostra specie. Harari è infatti in grado di analizzare il ruolo dell'uomo nel tempo presente, confrontando le nostre società con quelle antiche, descrivendo il funzionamento di alcuni aspetti della nostra vita particolarmente complessi a causa della grande innovazione a cui siamo costantemente esposti e offrendo molte chiavi di lettura e speculazione per un futuro a medio-breve termine. Non mancano inoltre piccole storie o vicende utili ad approfondire gli argomenti proposti. Non si tratta quindi un saggio puramente teorico, anche se il rischio dell'autore è tuttavia di apparire troppo 'prolisso' nell'esposizione delle proprie tesi.", 
        punteggio: 5,
        src: "https://www.ibs.it/images/9788845296499_0_536_0_75.jpg",
        link: "https://www.amazon.it/Sapiens-animali-Breve-storia-dellumanit%C3%A0/dp/8845296490/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=WEI089GNRYD0&keywords=homo+sapiens&qid=1666554827&qu=eyJxc2MiOiIyLjg1IiwicXNhIjoiMi40MCIsInFzcCI6IjIuMzYifQ%3D%3D&sprefix=homo+sapien%2Caps%2C161&sr=8-1",
    },
    {
        titolo: "Da zero a uno",
        citazione: "Il monopolio è la condizione di ogni business di successo",
        recensione : "Da più di vent'anni il cambiamento e l'innovazione sono in mano a poche start-up che sviluppano tutta la tecnologia con cui viviamo.Peter Thiel, già fondatore di Paypal e investitore precoce di Facebook e SpaceX, racconta con un linguaggio tecnico, senza fronzoli, ma accessibile a tutti il processo che sta dietro la nascita e la crescita di un'azienda altamente innovativa. Tramite l'analisi di alcuni case studies della Silicon Valley, è possibile infatti apprendere tutte le similarità tra i diversi esempi di successo nel settore e stilare una lista di buone pratiche per evitare il fallimento di un'azienda ancora in via di sviluppo e massimizzare le probabilità di successo.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71smRBsS57L.jpg",
        link: "https://www.amazon.it/segreti-startup-ovvero-costruisce-futuro/dp/8817080462/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1GMFO4F75D74D&keywords=da+zero+a+uno&qid=1666554841&qu=eyJxc2MiOiIxLjI5IiwicXNhIjoiMC44OCIsInFzcCI6IjAuNzUifQ%3D%3D&sprefix=da+zero+a+%2Caps%2C222&sr=8-1",
    },
    {
        titolo: "Tim Cook",
        citazione: "Non ho mai riconosciuta la mia sessualità pubblicamente. Quindi fatemi essere chiaro: sono fiero di esseregay",
        recensione : "Tim Cook è tutto l'opposto di Steve Jobs: un manager pubblicamente freddo, meno carismatico e creativo, senza una mente visionaria come il fondatore della Apple: malgrado ciò, come mai è stato scelto per succedere alla guida dell’azienda di Cupertino? Questa biografia cerca di indagarne i motivi partendo dall'infanzia di Cook e i suoi primi incarichi lavorativi, fino a mostrare le ragioni per cui il manager è riuscito a far progredire l'eredità di Jobs trasformando la Apple nell'azienda  più ricca al mondo. Consiglio di leggere questa biografia solo dopo aver letto quella di Jobs, in modo da poter cogliere maggiormente le differenze tra le due personalità, gli stili manageriali e i cambiamenti che vi sono stati sotto la direzione di entrambi.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/419maTdPYrL.jpg",
        link: "https://www.amazon.it/Cook-genio-cambiato-futuro-Apple/dp/8820067609/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1MZKCJRYRJQW7&keywords=tim+cook&qid=1666554850&qu=eyJxc2MiOiIxLjMxIiwicXNhIjoiMC45NyIsInFzcCI6IjAuODgifQ%3D%3D&sprefix=tim+co%2Caps%2C284&sr=8-1",
    },
    {
        titolo: "Momenti di trascurabile felicità",
        citazione: "Tutte le cose che bisogna fare, mi piace rimandarle, oppure averle già fatte.",
        recensione : "Tutti noi abbiamo i nostri intimi momenti di felicità che, in maniera inconsapevole, arricchiscono notevolmente le nostre vite, ma di cui spesso ci vergognamo. Prima di leggere questo libro nemmeno ci pensavo, eppure sono questi piccoli momenti a renderci felici nel quotidiano; non potremmo vivere altrimenti. Non vi resterà nulla di profondo da questa lettura, se non la consapevolezza che questi piccoli momenti esistono e fanno la differenza, perciò non trascurateli e non sottovalutateli. Non voglio far altro che incoraggiarvi a farci caso, a tenere traccia di questi momenti, a ricordarli quando siete annoiati e, quando ne avete la possibilità, a condividerli con le persone che preferite.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/61u6kJLydPL.jpg",
        link: "https://www.amazon.it/Momenti-trascurabile-felicit%C3%A0-Francesco-Piccolo/dp/8806219650/ref=sr_1_1?keywords=momenti+di+trascurabile+felicit%C3%A0&qid=1666554860&qu=eyJxc2MiOiIwLjgwIiwicXNhIjoiMC40MiIsInFzcCI6IjAuNDkifQ%3D%3D&sprefix=momenti+di+tr%2Caps%2C256&sr=8-1",
    },
    {
        titolo: "Let my people go surfing",
        citazione: "Non superare mai i tuoi limiti. Spingili al massimo e vivi per quei momenti, ma non andare oltre.",
        recensione : "Patagonia, Nike, The North Face, Carhart, Adidas...   Potrebbero sembrare tutti brand molto simili per prodotti, marketing e origine: eppure dietro la storia e i valori di Patagonia si cela una persona carismatica quanto riservata, il suo fondatore Yvon Chouinard, un uomo estremamente attento all'ambiente, alle sue responsabilità di imprenditore e all'impatto sociale della sua azienda. Patagonia di conseguenza, rispecchia questi valori e ribalta completamente tutte le lezioni sull'imprenditoria americana: non offre saldi di ogni tipo, aumenta i prezzi qualora necessario per garantire una maggiore sostenibilità sociale e ambientale, fa enormi donazioni in beneficenza a minuscole comunità in giro per il mondo e non si cura delle tendenze del mercato quando va contro i valori del brand.", 
        punteggio: 5,
        src: "https://www.ibs.it/images/9788865492611_0_536_0_75.jpg",
        link: "https://www.amazon.it/people-surfing-filosofia-imprenditore-ribelle/dp/8865492619/ref=sr_1_1?keywords=let+my+people+go+surfing&qid=1666554869&qu=eyJxc2MiOiIxLjQ1IiwicXNhIjoiMS4wNiIsInFzcCI6IjEuMjAifQ%3D%3D&sprefix=let+my%2Caps%2C250&sr=8-1",
    },
    {
        titolo: "Fahreneith 451",
        citazione: "Un libro è una pistola carica.",
        recensione : "Che cosa succede se si unisce il significato politico di un libro e un romanzo scritto in stile 1984? Un romanzo ambientato in un futuro distopico che non ha nulla da invidiare al capolavoro di George Orwell, ma che anzi, sotto certi punti di vista, ne è addirittura superiore. La trama dietro Fahreneit 451 è infatti meno romantica, ma allo stesso tempo più dinamica, incalzante e si concentra meno nella descrizione del regime totalitario in cui è ambientata la storia. Ne risulta una scrittura a cui è molto più facile appassionarsi, la lettura scorre velocemente nonostante il clima politico pesante caratteristico del romanzo e l'assurdità del contesto e il racconto è a tratti quasi esilarante per la presenza di situazioni tragi-comiche che spezzano la narrazione.", 
        punteggio: 4,
        src: "https://upload.wikimedia.org/wikipedia/en/d/db/Fahrenheit_451_1st_ed_cover.jpg",
        link: "https://www.amazon.it/Fahrenheit-451-Ray-Bradbury/dp/8804665297/ref=sr_1_1?keywords=fahrenheit+451&qid=1666554880&qu=eyJxc2MiOiIxLjYwIiwicXNhIjoiMC45MiIsInFzcCI6IjAuOTIifQ%3D%3D&sprefix=fahren%2Caps%2C399&sr=8-1",
    },
    {
        titolo: "L'unica regola è che non ci sono regole",
        citazione: "Non c'è nessuna politica. Usa il buon senso. Agisci nell'interesse di Netflix.",
        recensione : "La più grande 'non-regola' di Netflix è che ai dipendenti sono concesse ferie illimitate. Molte persone potrebbero di conseguenza pensare che i lavoratori spendono molto tempo in vacanza fuori ufficio; eppure, non solo questo non si verifica, ma i dipendenti dell'azienda intrattenitiva sono più responsabili e fedeli che mai al proprio datore di lavoro. I fondatori di Netflix spiegano infatti come sono riusciti a creare un ambiente in cui i controlli e le regole sono quasi assenti, in cui il lavoratore è libero di agire come preferisce e ciò nonostante, dove i dipendenti si comportano mettendo gli interessi della società al primo posto. Tutto ciò si ottiene solo in un modo, secondo gli autori: aumentando il talento in azienda, governando tramite principi e non regole e offrendo vantaggi e stipendi estremamente alti ai propri dipendenti.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/41aRXSNYHJL.jpg",
        link: "",
    },
    {
        titolo: "New York è una città senza tende",
        citazione: "Qualcuno dice che siccome Manhattan è un isola, per continuare a vivere è costretta a demolire e ricostruire.",
        recensione : "Conosciamo tutti New York come la città dell'Empire State Building, del toro di Wall Street, delle meraviglie di Central Park e delle opere d'arte del Moma. L'essenza della città e il come si vive nel quotidiano della Grande Mela ci sono tuttavia ignoti. Paolo Cognetti permette di conoscere i quartieri più iconici, ma più estranei agli occhi dei turisti, rivelando una città ben diversa dagli stereotipi e molto più intrisa di contraddizioni e sfumature etniche e culturali di quanto si pensi. Se siete già stati a New York, questo libro è l'occasione per cambiare punto di vista verso la città. In caso contrario resterete ancora più incuriositi dalla città più amata e discussa al mondo.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788858130421_0_424_0_75.jpg",
        link: "https://www.amazon.it/New-York-finestra-senza-tende/dp/8858130421/ref=sr_1_1?keywords=new+york+%C3%A8+una+finestra+senza+tende&qid=1666554917&qu=eyJxc2MiOiIwLjI5IiwicXNhIjoiMC4wOCIsInFzcCI6IjAuMjMifQ%3D%3D&sprefix=new+york+%C3%A8%2Caps%2C231&sr=8-1",
    },
    {
        titolo: "The Hate u Give",
        citazione: "Thug Life stood for 'The Hate U Give Little Infants Fucks Everybody'",
        recensione : "Dopo l'omicidio di George Floyd del 2020, il movimento 'Black Lives Matter' ha guadagnato ancora più visibilità e per me il modo migliore per avvicinarmii a queste tematiche è stato leggere questo romanzo verosimile, in cui l'oppressione razziale e i pregiudizi a cui sono ancora sottoposte molte persone di colore sono raccontati dal punto di vista di una giovane ragazza, talvolta incapace di comprendere e quasi ingenua di fronte alle situazioni paradossali che si trova ad affrontare per via delle sue origini. Leggere questo libro in lingua originale è stato sicuramente un valore aggiunto: mi ha permesso di immergermi, grazie allo 'slang' e ai modi di fare descritti, nella vita del protagonista e nel contesto sociale in cui è ambientato il romanzo.", 
        punteggio: 3,
        src: "https://www.ibs.it/images/9788809836402_0_536_0_75.jpg",
        link: "https://www.amazon.it/Hate-Give-coraggio-della-verit%C3%A0/dp/8809909909/ref=sr_1_1?keywords=the+hate+u+give&qid=1666554940&qu=eyJxc2MiOiIyLjQyIiwicXNhIjoiMi4wOSIsInFzcCI6IjIuMTIifQ%3D%3D&sprefix=the+hate%2Caps%2C634&sr=8-1",
    },
    {
        titolo: "After Dark",
        citazione: "La memoria umana è veramente strana: c'è conservata dentro un sacco di roba inutile, un sacco di cianfrusaglie.",
        recensione : "Definirei After Dark come il libro senza trama.   Più che di un romanzo, si tratta infatti di una narrazione di situazioni, stati d'animo e relazioni tra i personaggi e non vi è un filo logico conduttore che lega i capitoli del libro. Ciò nonostante durante la lettura ci si immerge nell'ambientazione del libro che, per quanto possa sembrare paradossale, è costruita a partire da un reale quartiere di Tokyo. Non vi aspettate di capire qualcosa o imparare nulla da questo libro, piuttosto divertitevi e godetevi la lettura come se non dovesse restarvi nulla al termine del libro.",  
        punteggio: 3,
        src: "https://www.ibs.it/images/9788806217006_0_536_0_75.jpg",
        link: "https://www.amazon.it/After-dark-Haruki-Murakami/dp/8806217003/ref=sr_1_1?crid=2X4ISDSJZC33J&keywords=after+dark+murakami&qid=1666554955&qu=eyJxc2MiOiIwLjgwIiwicXNhIjoiMC41NyIsInFzcCI6IjAuNTEifQ%3D%3D&sprefix=after+da%2Caps%2C419&sr=8-1",
    },
    {
        titolo: "La mia vita per la libertà",
        citazione: "Voi occidentali, avete l'ora ma non avete mai il tempo.",
        recensione : "Ovviamente conoscevo Gandhi per la sua scelta nonviolenta, per cui, da amante delle storie di personaggi storici e di successo, mi sono immerso nella lettura dell'autobiografia del Mahatma. Ho approfondito la sua ideologia e il contesto in cui si è ritrovato ad agire, felice tuttavia di essere in disaccordo su alcune tematiche e avendo potuto sviluppare meglio il mio punto di vista verso alcuni problemi sociali e politici del nostro tempo. Non si tratta né di una lettura divertente, né facile, ma è una buona occasione per mettersi alla propria, imparare dal passato e provare a sviluppare una propria mentalità per diventare più critici e consapevoli verso il mondo che ci circonda.", 
        punteggio: 3,
        src: "https://m.media-amazon.com/images/I/61SHXU6a9DL.jpg",
        link: "https://www.amazon.it/libert%C3%A0-Lautobiografia-profeta-della-non-violenza/dp/8854171654/ref=sr_1_1?keywords=la+mia+vita+per+la+libert%C3%A0&qid=1666554968&qu=eyJxc2MiOiIxLjA5IiwicXNhIjoiMC41OSIsInFzcCI6IjAuNzIifQ%3D%3D&sprefix=la+mia+vita+per+la+liber%2Caps%2C179&sr=8-1",
    },
    {
        titolo: "Il Potere delle Abitudini",
        citazione: "I campioni non fanno cose straordinarie. Fanno cose normali seguendo un abitudine.",
        recensione : "Sono abbastanza convinto che questo libro abbia rivoluzionato il modo di concepire e vivere la mia quotidianità. Posso dire infatti che ormai, svolgo la maggior parte delle mie attività per semplice abitudine. Per quanto possa sembrare monotono e noioso, essere delle persone guidate da solide routine comporta numerosi vantaggi: oltre a essere più efficienti e produttivi, si spreca meno e fatica per decidere come e quando agire. Non vi garantisco che questo libro genererà gli stessi effetti  in voi, ma sicuramente cambierete idea riguardo il funzionamento del nostro cervello e leggerete numerosi consigli pratici su come implementare abitudini un'abitudine nella nostra quotidianità.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/715dxFl2lSL.jpg",
        link: "https://www.amazon.it/potere-abitudini-formano-condizionano-cambiarle/dp/8850236905/ref=sr_1_1?keywords=il+potere+delle+abitudini&qid=1666554978&qu=eyJxc2MiOiIwLjgxIiwicXNhIjoiMC4zOSIsInFzcCI6IjAuMjgifQ%3D%3D&sprefix=il+potere+de%2Caps%2C184&sr=8-1",
    },
    {
        titolo: "Kafka sulla Spiaggia",
        citazione: "Poesia e simbolismo sono sempre stati inseparabili. Come i pirati e il rum.",
        recensione : "Non ricordo molto della lettura di questo romanzo, se non che è stato il primo di Murakami e quello che mi ha fatto appassionare al modo di scrivere dell'autore giapponese. In 'Kafka sulla spiaggia' il reale si confonde con l'immaginario, la vita quotidiana con il sogno, le azioni dei personaggi con i loro pensieri più intimi, fino a creare una situazione surreale in cui immergersi e di cui, almeno inizialmente, si capisce ben poco. E' questo tuttavia il punto forte di questo libro: aspettatevi tutto il contrario di una trama lineare, personaggi razionali e una narrazione logica e verosimile. Nulla infatti, si può dare per certo nella lettura di questo romanzo.", 
        punteggio: 5,
        src: "https://m.media-amazon.com/images/I/61R0XpGhHgL.jpg",
        link: "https://www.amazon.it/Kafka-sulla-spiaggia-Haruki-Murakami/dp/8806216945/ref=sr_1_1?keywords=kafka+sulla+spiaggia+murakami&qid=1666554989&qu=eyJxc2MiOiIwLjk3IiwicXNhIjoiMC41MSIsInFzcCI6IjAuNDAifQ%3D%3D&sprefix=kafka+sulla%2Caps%2C209&sr=8-1",
    },
    {
        titolo: "L'ordine del Tempo",
        citazione: "Il tempo passa più velocemente in montagna che in collina.",
        recensione : "Ho letto questo libro tre volte e sono convinto di non averne ancora compreso appieno il contenuto, ma sono certo tuttavia che la mia concezione riguardo lo ‘scorrere del tempo’ sia stata completamente rivoluzionata. Che voi siate degli appassionati di fisica o meno e a prescindere da quanto capirete dalle parti più tecniche del testo di Rovelli, scoprirete alcune verità su questa branca della scienza che, nonostante non abbiano alcuna applicazione nel quotidiano, conferiranno una maggiore comprensione di come, in maniera del tutto controintuitiva e inaspettata, funziona il mondo in cui viviamo.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/71GL+ee5ddL.jpg",
        link: "https://www.amazon.it/Lordine-del-tempo-Carlo-Rovelli/dp/8845931927/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3AKZZF3K9NAAY&keywords=l%27ordine+del+tempo&qid=1666555000&qu=eyJxc2MiOiIwLjQ3IiwicXNhIjoiMC4zMCIsInFzcCI6IjAuMjQifQ%3D%3D&sprefix=l+ordine+del+tem%2Caps%2C205&sr=8-1",
    },
    {
        titolo: "Il Nome della Rosa",
        citazione: "Spesso sono gli inquisitori a creare gli eretici.",
        recensione : "Leggere il capolavoro di Umberto Eco ha suscitato in me sensazioni contrastanti: la trama intrigante e incalzante mi motivava a perseguire nella lettura, l’ambientazione, un monastero benedettino isolato dalla società, così lontana e inimmaginabile per un ragazzo del terzo millennio, mi incuriosiva, mentre le interminabili e dettagliatissime descrizioni di ogni cosa, persona o avvenimento tendevano ad annoiarmi e a farmi leggere con distrazione quelle parti del libro. Il problema de ‘Il Nome della Rosa’ è rappresentato tuttavia dall’omonimo film, realizzato con estrema cura dei particolari e con fedeltà rispetto al testo: il rischio è che il lettore si lasci ‘impigrire’ dalla lunghezza del libro in favore di una più facile e leggera visione della pellicola.", 
        punteggio: 4,
        src: "https://m.media-amazon.com/images/I/81dhmnbA1VL.jpg",
        link: "https://www.amazon.it/nome-della-rosa-Ediz-illustrata/dp/8834603001/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1LVL1YP35Z1LT&keywords=il+nome+della+rosa&qid=1666555010&qu=eyJxc2MiOiIyLjIxIiwicXNhIjoiMS4yNyIsInFzcCI6IjEuMTcifQ%3D%3D&sprefix=il+nome+della+ro%2Caps%2C190&sr=8-1",
    },
    {
        titolo: "L'estate che conobbi il Che",
        citazione: "«Ma cosa c’entra la scuola con la rivoluzione?» «Cesare, la rivoluzione si fa con le idee, non con i fucili».",
        recensione : "Come fa il Che Guevara a entrare in modo definitivo nella vita di Cesare, tipico ragazzo brianzolo poco interessato alla politica e alla storia? Garlando, come già dimostrato nei suoi precedenti romanzi, riesce a raccontare la storia di grandi personaggi storici, lontanissimi geograficamente e cronologicamente, ‘trasportandoli’ in un contesto a noi molto più vicino. Le storie dei due protagonisti infatti, il Che e Cesare, si intrecciano inizialmente quasi per caso, dando vita a una narrazione che procede man mano nel testo, ma resta connessa con la vita ‘mondana’ dell’adolescente che, grazie alla relazione con il Che, ha l’occasione di scoprire molto sulla sua famiglia e di crescere notevolmente dal punto di vista personale.", 
        punteggio: 4,
        src: "https://www.rizzolilibri.it/content/uploads/2015/04/17/278764/3253969-9788817080040.png",
        link: "https://www.amazon.it/Lestate-che-conobbi-Luigi-Garlando/dp/8817096466/ref=sr_1_1?keywords=l+estate+che+conobbi+il+che&qid=1666555026&qu=eyJxc2MiOiIwLjc2IiwicXNhIjoiMC40MiIsInFzcCI6IjAuMjYifQ%3D%3D&sprefix=l%27estate+che+conob%2Caps%2C183&sr=8-1",
    },
    {
        titolo: "La sottile arte di fare quello che cazzo ti pare",
        citazione: "La società confonde l'attenzione con il successo. Il semplice fatto di poter scegliere i valori per cui sbatterci ci rende persone di successo.",
        recensione : "Il titolo del libro potrebbe essere frainteso per il linguaggio utilizzato, eppure l'autore invita veramente a fare ‘quel cazzo che vogliamo’, ossia a conferire molta meno importanza a tutte le aspettative della società e a impegnare il nostro tempo in ciò che veramente conferisce valore alle nostre vite. La chiave per essere felici e soddisfatti delle proprie giornate è rappresentata proprio da questo: essere estremamente selettivi verso ciò per cui decidiamo di impegnarci, abbandonare completamente la mentalità che spinge a fare sempre di più e limitare le nostre attività a ciò in cui crediamo realmente.", 
        punteggio: 4,
        src: "https://www.ibs.it/images/9788822707475_0_536_0_75.jpg",
        link: "https://www.amazon.it/scorretto-efficace-liberarsi-irritanti-problemi/dp/8822707451/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=",
    },
    




]
